; ============================================================
; LLVM IR generated by tscl compiler
; ============================================================

target triple = "arm64-apple-darwin"

; External declarations
declare i32 @printf(i8*, ...)
declare i32 @sprintf(i8*, i8*, ...)
declare i8* @malloc(i64)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)

; String constants
@.fmt_num = private unnamed_addr constant [4 x i8] c"%g\0A\00"
@.fmt_str = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_num2str = private unnamed_addr constant [3 x i8] c"%g\00"
@.str.0 = private unnamed_addr constant [4 x i8] c"run\00"
@.str.1 = private unnamed_addr constant [8 x i8] c"command\00"
@.str.2 = private unnamed_addr constant [1 x i8] c"\00"
@.str.3 = private unnamed_addr constant [10 x i8] c"inputFile\00"
@.str.4 = private unnamed_addr constant [11 x i8] c"outputFile\00"
@.str.5 = private unnamed_addr constant [7 x i8] c"emitIr\00"
@.str.6 = private unnamed_addr constant [8 x i8] c"emitAst\00"
@.str.7 = private unnamed_addr constant [8 x i8] c"verbose\00"
@.str.8 = private unnamed_addr constant [6 x i8] c"build\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"ir\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"ast\00"
@.str.11 = private unnamed_addr constant [6 x i8] c"check\00"
@.str.12 = private unnamed_addr constant [5 x i8] c"llvm\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"-o\00"
@.str.14 = private unnamed_addr constant [9 x i8] c"--output\00"
@.str.15 = private unnamed_addr constant [10 x i8] c"--emit-ir\00"
@.str.16 = private unnamed_addr constant [11 x i8] c"--emit-ast\00"
@.str.17 = private unnamed_addr constant [3 x i8] c"-v\00"
@.str.18 = private unnamed_addr constant [10 x i8] c"--verbose\00"
@.str.19 = private unnamed_addr constant [27 x i8] c"tscl - TypeScript Compiler\00"
@.str.20 = private unnamed_addr constant [40 x i8] c"Usage: tscl <command> [options] <input>\00"
@.str.21 = private unnamed_addr constant [10 x i8] c"Commands:\00"
@.str.22 = private unnamed_addr constant [31 x i8] c"  run <file>      Run the file\00"
@.str.23 = private unnamed_addr constant [38 x i8] c"  build <file>    Compile to bytecode\00"
@.str.24 = private unnamed_addr constant [46 x i8] c"  llvm <file>     Generate LLVM IR (.ll file)\00"
@.str.25 = private unnamed_addr constant [46 x i8] c"  check <file>    Type check and borrow check\00"
@.str.26 = private unnamed_addr constant [33 x i8] c"  ir <file>       Output tscl IR\00"
@.str.27 = private unnamed_addr constant [29 x i8] c"  ast <file>      Output AST\00"
@.str.28 = private unnamed_addr constant [9 x i8] c"Options:\00"
@.str.29 = private unnamed_addr constant [30 x i8] c"  -o, --output    Output file\00"
@.str.30 = private unnamed_addr constant [34 x i8] c"  --emit-ir       Emit IR to file\00"
@.str.31 = private unnamed_addr constant [35 x i8] c"  --emit-ast      Emit AST to file\00"
@.str.32 = private unnamed_addr constant [33 x i8] c"  -v, --verbose   Verbose output\00"
@.str.33 = private unnamed_addr constant [33 x i8] c"  --help          Show this help\00"
@.str.34 = private unnamed_addr constant [14 x i8] c"Tokenizing...\00"
@.str.35 = private unnamed_addr constant [3 x i8] c"  \00"
@.str.36 = private unnamed_addr constant [8 x i8] c" tokens\00"
@.str.37 = private unnamed_addr constant [11 x i8] c"Parsing...\00"
@.str.38 = private unnamed_addr constant [12 x i8] c"Parse error\00"
@.str.39 = private unnamed_addr constant [5 x i8] c"body\00"
@.str.40 = private unnamed_addr constant [12 x i8] c" statements\00"
@.str.41 = private unnamed_addr constant [18 x i8] c"Lowering to IR...\00"
@.str.42 = private unnamed_addr constant [18 x i8] c"IR lowering error\00"
@.str.43 = private unnamed_addr constant [10 x i8] c"functions\00"
@.str.44 = private unnamed_addr constant [11 x i8] c" functions\00"
@.str.45 = private unnamed_addr constant [16 x i8] c"Verifying IR...\00"
@.str.46 = private unnamed_addr constant [23 x i8] c"IR verification failed\00"
@.str.47 = private unnamed_addr constant [21 x i8] c"Compilation complete\00"
@.str.48 = private unnamed_addr constant [31 x i8] c"Error: No input file specified\00"
@.str.49 = private unnamed_addr constant [3 x i8] c"fs\00"
@.str.50 = private unnamed_addr constant [11 x i8] c"existsSync\00"
@.str.51 = private unnamed_addr constant [24 x i8] c"Error: File not found: \00"
@.str.52 = private unnamed_addr constant [5 x i8] c"utf8\00"
@.str.53 = private unnamed_addr constant [13 x i8] c"readFileSync\00"
@.str.54 = private unnamed_addr constant [5 x i8] c"JSON\00"
@.str.55 = private unnamed_addr constant [10 x i8] c"stringify\00"
@.str.56 = private unnamed_addr constant [19 x i8] c"Checking source...\00"
@.str.57 = private unnamed_addr constant [10 x i8] c"  Parsed \00"
@.str.58 = private unnamed_addr constant [7 x i8] c"Passes\00"
@.str.59 = private unnamed_addr constant [9 x i8] c"checkAst\00"
@.str.60 = private unnamed_addr constant [7 x i8] c"errors\00"
@.str.61 = private unnamed_addr constant [21 x i8] c"Borrow check errors:\00"
@.str.62 = private unnamed_addr constant [12 x i8] c"BorrowCheck\00"
@.str.63 = private unnamed_addr constant [12 x i8] c"formatError\00"
@.str.64 = private unnamed_addr constant [10 x i8] c"typecheck\00"
@.str.65 = private unnamed_addr constant [20 x i8] c"  Type check passed\00"
@.str.66 = private unnamed_addr constant [9 x i8] c"optimize\00"
@.str.67 = private unnamed_addr constant [22 x i8] c"  Optimization passed\00"
@.str.68 = private unnamed_addr constant [18 x i8] c"  Verifying IR...\00"
@.str.69 = private unnamed_addr constant [14 x i8] c"  IR verified\00"
@.str.70 = private unnamed_addr constant [15 x i8] c"Check passed: \00"
@.str.71 = private unnamed_addr constant [14 x i8] c"writeFileSync\00"
@.str.72 = private unnamed_addr constant [24 x i8] c"Compiling to LLVM IR...\00"
@.str.73 = private unnamed_addr constant [19 x i8] c"Compilation failed\00"
@.str.74 = private unnamed_addr constant [22 x i8] c"Generating LLVM IR...\00"
@.str.75 = private unnamed_addr constant [6 x i8] c".tscl\00"
@.str.76 = private unnamed_addr constant [8 x i8] c"indexOf\00"
@.str.77 = private unnamed_addr constant [12 x i8] c"Generated: \00"
@.str.78 = private unnamed_addr constant [29 x i8] c"To compile to native binary:\00"
@.str.79 = private unnamed_addr constant [21 x i8] c"  llc -filetype=obj \00"
@.str.80 = private unnamed_addr constant [13 x i8] c" -o output.o\00"
@.str.81 = private unnamed_addr constant [27 x i8] c"  clang output.o -o output\00"
@.str.82 = private unnamed_addr constant [10 x i8] c"substring\00"
@.str.83 = private unnamed_addr constant [4 x i8] c".ll\00"
@.str.84 = private unnamed_addr constant [25 x i8] c"Compiling to bytecode...\00"
@.str.85 = private unnamed_addr constant [27 x i8] c"Compiling for execution...\00"
@.str.86 = private unnamed_addr constant [8 x i8] c"Emitter\00"
@.str.87 = private unnamed_addr constant [11 x i8] c"compileAst\00"
@.str.88 = private unnamed_addr constant [27 x i8] c"Bytecode generation failed\00"
@.str.89 = private unnamed_addr constant [13 x i8] c"  Generated \00"
@.str.90 = private unnamed_addr constant [7 x i8] c" bytes\00"
@.str.91 = private unnamed_addr constant [4 x i8] c".bc\00"
@.str.92 = private unnamed_addr constant [9 x i8] c"bytecode\00"
@.str.93 = private unnamed_addr constant [16 x i8] c"writeBinaryFile\00"
@.str.94 = private unnamed_addr constant [11 x i8] c"Compiled: \00"
@.str.95 = private unnamed_addr constant [5 x i8] c" -> \00"
@.str.96 = private unnamed_addr constant [3 x i8] c" (\00"
@.str.97 = private unnamed_addr constant [8 x i8] c" bytes)\00"
@.str.98 = private unnamed_addr constant [21 x i8] c"Bytecode generated (\00"
@.str.99 = private unnamed_addr constant [67 x i8] c"To run, use the VM: ./target/release/script --run-binary <file.bc>\00"
@.str.100 = private unnamed_addr constant [14 x i8] c"compileSource\00"
@.str.101 = private unnamed_addr constant [8 x i8] c"compile\00"
@.str.102 = private unnamed_addr constant [9 x i8] c"__anon_1\00"
@.str.103 = private unnamed_addr constant [18 x i8] c"compileToBytecode\00"
@.str.104 = private unnamed_addr constant [9 x i8] c"__anon_2\00"
@.str.105 = private unnamed_addr constant [14 x i8] c"compileToLlvm\00"
@.str.106 = private unnamed_addr constant [12 x i8] c"parseSource\00"
@.str.107 = private unnamed_addr constant [6 x i8] c"parse\00"
@.str.108 = private unnamed_addr constant [9 x i8] c"tokenize\00"
@.str.109 = private unnamed_addr constant [17 x i8] c"lowerProgramToIr\00"
@.str.110 = private unnamed_addr constant [10 x i8] c"lowerToIr\00"
@.str.111 = private unnamed_addr constant [15 x i8] c"verifyIrModule\00"
@.str.112 = private unnamed_addr constant [9 x i8] c"verifyIr\00"
@.str.113 = private unnamed_addr constant [18 x i8] c"serializeIrModule\00"
@.str.114 = private unnamed_addr constant [12 x i8] c"serializeIr\00"
@.str.115 = private unnamed_addr constant [16 x i8] c"codegenIrModule\00"
@.str.116 = private unnamed_addr constant [10 x i8] c"codegenIr\00"
@.str.117 = private unnamed_addr constant [15 x i8] c"emitLlvmModule\00"
@.str.118 = private unnamed_addr constant [9 x i8] c"emitLlvm\00"
@.str.119 = private unnamed_addr constant [10 x i8] c"TypeCheck\00"
@.str.120 = private unnamed_addr constant [10 x i8] c"Optimizer\00"
@.str.121 = private unnamed_addr constant [6 x i8] c"0.4.0\00"
@.str.122 = private unnamed_addr constant [8 x i8] c"version\00"
@.str.123 = private unnamed_addr constant [24 x i8] c"tscl compiler loaded (v\00"
@.str.124 = private unnamed_addr constant [2 x i8] c")\00"
@.str.125 = private unnamed_addr constant [9 x i8] c"__args__\00"
@.str.126 = private unnamed_addr constant [10 x i8] c"undefined\00"

; ============================================================
; Runtime functions
; ============================================================

define i64 @tscl_console_log(i64 %value) {
entry:
  ; Check if value is a string (high bits = 0xFFFC)
  %high = lshr i64 %value, 48
  %is_str = icmp eq i64 %high, 65532
  br i1 %is_str, label %print_str, label %print_num
print_str:
  ; Extract pointer (mask off the tag)
  %ptr_int = and i64 %value, 281474976710655
  %ptr = inttoptr i64 %ptr_int to i8*
  %fmt_s = getelementptr [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt_s, i8* %ptr)
  br label %done
print_num:
  %dval = bitcast i64 %value to double
  %fmt_n = getelementptr [4 x i8], [4 x i8]* @.fmt_num, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt_n, double %dval)
  br label %done
done:
  ret i64 9221120237041090561
}

define i8* @tscl_num_to_str(i64 %num) {
entry:
  %buf = call i8* @malloc(i64 32)
  %dval = bitcast i64 %num to double
  %fmt = getelementptr [3 x i8], [3 x i8]* @.fmt_num2str, i64 0, i64 0
  call i32 (i8*, i8*, ...) @sprintf(i8* %buf, i8* %fmt, double %dval)
  ret i8* %buf
}

define i64 @tscl_add_any(i64 %a, i64 %b) {
entry:
  ; Check if either operand is a string (high 16 bits = 0xFFFC = 65532)
  %a_high = lshr i64 %a, 48
  %b_high = lshr i64 %b, 48
  %a_is_str = icmp eq i64 %a_high, 65532
  %b_is_str = icmp eq i64 %b_high, 65532
  %either_str = or i1 %a_is_str, %b_is_str
  br i1 %either_str, label %check_types, label %do_add
do_add:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %result_fp = fadd double %a_fp, %b_fp
  %result_num = bitcast double %result_fp to i64
  ret i64 %result_num
check_types:
  ; Get string pointer for a (convert if needed)
  br i1 %a_is_str, label %a_already_str, label %convert_a
a_already_str:
  %a_ptr_int1 = and i64 %a, 281474976710655
  %a_ptr1 = inttoptr i64 %a_ptr_int1 to i8*
  br label %got_a_ptr
convert_a:
  %a_ptr2 = call i8* @tscl_num_to_str(i64 %a)
  br label %got_a_ptr
got_a_ptr:
  %a_ptr = phi i8* [%a_ptr1, %a_already_str], [%a_ptr2, %convert_a]
  ; Get string pointer for b (convert if needed)
  br i1 %b_is_str, label %b_already_str, label %convert_b
b_already_str:
  %b_ptr_int1 = and i64 %b, 281474976710655
  %b_ptr1 = inttoptr i64 %b_ptr_int1 to i8*
  br label %got_b_ptr
convert_b:
  %b_ptr2 = call i8* @tscl_num_to_str(i64 %b)
  br label %got_b_ptr
got_b_ptr:
  %b_ptr = phi i8* [%b_ptr1, %b_already_str], [%b_ptr2, %convert_b]
  ; Concatenate the strings
  %a_len = call i64 @strlen(i8* %a_ptr)
  %b_len = call i64 @strlen(i8* %b_ptr)
  %total_len = add i64 %a_len, %b_len
  %alloc_len = add i64 %total_len, 1
  %new_buf = call i8* @malloc(i64 %alloc_len)
  call i8* @strcpy(i8* %new_buf, i8* %a_ptr)
  call i8* @strcat(i8* %new_buf, i8* %b_ptr)
  ; Tag the result as a string
  %new_int = ptrtoint i8* %new_buf to i64
  %new_masked = and i64 %new_int, 281474976710655
  %result_str = or i64 %new_masked, 18445618173802708992
  ret i64 %result_str
}

define i64 @tscl_sub_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %result_fp = fsub double %a_fp, %b_fp
  %result = bitcast double %result_fp to i64
  ret i64 %result
}

define i64 @tscl_mul_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %result_fp = fmul double %a_fp, %b_fp
  %result = bitcast double %result_fp to i64
  ret i64 %result
}

define i64 @tscl_div_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %result_fp = fdiv double %a_fp, %b_fp
  %result = bitcast double %result_fp to i64
  ret i64 %result
}

define i64 @tscl_mod_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %result_fp = frem double %a_fp, %b_fp
  %result = bitcast double %result_fp to i64
  ret i64 %result
}

define i64 @tscl_neg(i64 %a) {
entry:
  %a_fp = bitcast i64 %a to double
  %result_fp = fsub double 0.0, %a_fp
  %result = bitcast double %result_fp to i64
  ret i64 %result
}

define i64 @tscl_lt_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %cmp = fcmp olt double %a_fp, %b_fp
  %cmp_ext = zext i1 %cmp to i64
  %result = or i64 9221120237041090560, %cmp_ext
  ret i64 %result
}

define i64 @tscl_le_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %cmp = fcmp ole double %a_fp, %b_fp
  %cmp_ext = zext i1 %cmp to i64
  %result = or i64 9221120237041090560, %cmp_ext
  ret i64 %result
}

define i64 @tscl_gt_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %cmp = fcmp ogt double %a_fp, %b_fp
  %cmp_ext = zext i1 %cmp to i64
  %result = or i64 9221120237041090560, %cmp_ext
  ret i64 %result
}

define i64 @tscl_ge_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %cmp = fcmp oge double %a_fp, %b_fp
  %cmp_ext = zext i1 %cmp to i64
  %result = or i64 9221120237041090560, %cmp_ext
  ret i64 %result
}

define i64 @tscl_eq_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %cmp = fcmp oeq double %a_fp, %b_fp
  %cmp_ext = zext i1 %cmp to i64
  %result = or i64 9221120237041090560, %cmp_ext
  ret i64 %result
}

define i64 @tscl_ne_any(i64 %a, i64 %b) {
entry:
  %a_fp = bitcast i64 %a to double
  %b_fp = bitcast i64 %b to double
  %cmp = fcmp one double %a_fp, %b_fp
  %cmp_ext = zext i1 %cmp to i64
  %result = or i64 9221120237041090560, %cmp_ext
  ret i64 %result
}

define i64 @tscl_alloc_array(i64 %cap) {
entry:
  ; Allocate: 2 header i64s + cap elements
  %header_size = add i64 16, 0
  %elem_bytes = mul i64 %cap, 8
  %total_size = add i64 %header_size, %elem_bytes
  %ptr = call i8* @malloc(i64 %total_size)
  %arr = bitcast i8* %ptr to i64*
  ; Store capacity at offset 0
  store i64 %cap, i64* %arr
  ; Store length (0) at offset 1
  %len_ptr = getelementptr i64, i64* %arr, i64 1
  store i64 0, i64* %len_ptr
  ; Tag pointer as array (0xFFFB prefix)
  %ptr_int = ptrtoint i64* %arr to i64
  %masked = and i64 %ptr_int, 281474976710655
  %tagged = or i64 %masked, 18444492273895866368
  ret i64 %tagged
}

define void @tscl_array_set(i64 %arr_tagged, i64 %idx_val, i64 %value) {
entry:
  ; Extract array pointer
  %ptr_int = and i64 %arr_tagged, 281474976710655
  %arr = inttoptr i64 %ptr_int to i64*
  ; Convert index from NaN-boxed double to integer
  %idx_fp = bitcast i64 %idx_val to double
  %idx = fptosi double %idx_fp to i64
  ; Elements start at offset 2 (after capacity and length)
  %elem_offset = add i64 %idx, 2
  %elem_ptr = getelementptr i64, i64* %arr, i64 %elem_offset
  store i64 %value, i64* %elem_ptr
  ; Update length if needed (idx + 1 > length)
  %len_ptr = getelementptr i64, i64* %arr, i64 1
  %curr_len = load i64, i64* %len_ptr
  %new_len = add i64 %idx, 1
  %need_update = icmp sgt i64 %new_len, %curr_len
  br i1 %need_update, label %update_len, label %done
update_len:
  store i64 %new_len, i64* %len_ptr
  br label %done
done:
  ret void
}

define i64 @tscl_array_get(i64 %arr_tagged, i64 %idx_val) {
entry:
  ; Extract array pointer
  %ptr_int = and i64 %arr_tagged, 281474976710655
  %arr = inttoptr i64 %ptr_int to i64*
  ; Convert index from NaN-boxed double to integer
  %idx_fp = bitcast i64 %idx_val to double
  %idx = fptosi double %idx_fp to i64
  ; Elements start at offset 2
  %elem_offset = add i64 %idx, 2
  %elem_ptr = getelementptr i64, i64* %arr, i64 %elem_offset
  %value = load i64, i64* %elem_ptr
  ret i64 %value
}

define i64 @tscl_array_length(i64 %arr_tagged) {
entry:
  ; Extract array pointer
  %ptr_int = and i64 %arr_tagged, 281474976710655
  %arr = inttoptr i64 %ptr_int to i64*
  ; Length is at offset 1
  %len_ptr = getelementptr i64, i64* %arr, i64 1
  %len = load i64, i64* %len_ptr
  ; Convert to NaN-boxed double
  %len_fp = sitofp i64 %len to double
  %result = bitcast double %len_fp to i64
  ret i64 %result
}

define i64 @tscl_array_push(i64 %arr_tagged, i64 %value) {
entry:
  ; Extract array pointer
  %ptr_int = and i64 %arr_tagged, 281474976710655
  %arr = inttoptr i64 %ptr_int to i64*
  ; Get current length
  %len_ptr = getelementptr i64, i64* %arr, i64 1
  %len = load i64, i64* %len_ptr
  ; Store element at length index (offset 2 + len)
  %elem_offset = add i64 %len, 2
  %elem_ptr = getelementptr i64, i64* %arr, i64 %elem_offset
  store i64 %value, i64* %elem_ptr
  ; Increment length
  %new_len = add i64 %len, 1
  store i64 %new_len, i64* %len_ptr
  ; Return new length as NaN-boxed double
  %len_fp = sitofp i64 %new_len to double
  %result = bitcast double %len_fp to i64
  ret i64 %result
}

define i64 @tscl_alloc_object(i64 %cap) {
entry:
  ; Allocate: 2 header i64s + cap * 2 (key-value pairs)
  %header_size = add i64 16, 0
  %entry_count = mul i64 %cap, 2
  %entry_bytes = mul i64 %entry_count, 8
  %total_size = add i64 %header_size, %entry_bytes
  %ptr = call i8* @malloc(i64 %total_size)
  %obj = bitcast i8* %ptr to i64*
  ; Store capacity at offset 0
  store i64 %cap, i64* %obj
  ; Store count (0) at offset 1
  %count_ptr = getelementptr i64, i64* %obj, i64 1
  store i64 0, i64* %count_ptr
  ; Tag pointer as object (0xFFFA prefix)
  %ptr_int = ptrtoint i64* %obj to i64
  %masked = and i64 %ptr_int, 281474976710655
  %tagged = or i64 %masked, 18443366373989023744
  ret i64 %tagged
}

define void @tscl_object_set(i64 %obj_tagged, i64 %key, i64 %value) {
entry:
  ; Extract object pointer
  %ptr_int = and i64 %obj_tagged, 281474976710655
  %obj = inttoptr i64 %ptr_int to i64*
  ; Get count
  %count_ptr = getelementptr i64, i64* %obj, i64 1
  %count = load i64, i64* %count_ptr
  ; Search for existing key
  br label %search_loop
search_loop:
  %i = phi i64 [0, %entry], [%i_next, %search_continue]
  %found = icmp slt i64 %i, %count
  br i1 %found, label %check_key, label %not_found
check_key:
  ; Key is at offset 2 + i*2
  %key_offset = mul i64 %i, 2
  %key_idx = add i64 %key_offset, 2
  %key_ptr = getelementptr i64, i64* %obj, i64 %key_idx
  %stored_key = load i64, i64* %key_ptr
  %key_match = icmp eq i64 %stored_key, %key
  br i1 %key_match, label %update_value, label %search_continue
search_continue:
  %i_next = add i64 %i, 1
  br label %search_loop
update_value:
  ; Value is at offset 2 + i*2 + 1
  %val_idx = add i64 %key_idx, 1
  %val_ptr = getelementptr i64, i64* %obj, i64 %val_idx
  store i64 %value, i64* %val_ptr
  ret void
not_found:
  ; Add new entry at count position
  %new_key_offset = mul i64 %count, 2
  %new_key_idx = add i64 %new_key_offset, 2
  %new_key_ptr = getelementptr i64, i64* %obj, i64 %new_key_idx
  store i64 %key, i64* %new_key_ptr
  %new_val_idx = add i64 %new_key_idx, 1
  %new_val_ptr = getelementptr i64, i64* %obj, i64 %new_val_idx
  store i64 %value, i64* %new_val_ptr
  ; Increment count
  %new_count = add i64 %count, 1
  store i64 %new_count, i64* %count_ptr
  ret void
}

define i64 @tscl_object_get(i64 %obj_tagged, i64 %key) {
entry:
  ; Extract object pointer
  %ptr_int = and i64 %obj_tagged, 281474976710655
  %obj = inttoptr i64 %ptr_int to i64*
  ; Get count
  %count_ptr = getelementptr i64, i64* %obj, i64 1
  %count = load i64, i64* %count_ptr
  ; Search for key
  br label %search_loop
search_loop:
  %i = phi i64 [0, %entry], [%i_next, %search_continue]
  %in_bounds = icmp slt i64 %i, %count
  br i1 %in_bounds, label %check_key, label %not_found
check_key:
  ; Key is at offset 2 + i*2
  %key_offset = mul i64 %i, 2
  %key_idx = add i64 %key_offset, 2
  %key_ptr = getelementptr i64, i64* %obj, i64 %key_idx
  %stored_key = load i64, i64* %key_ptr
  %key_match = icmp eq i64 %stored_key, %key
  br i1 %key_match, label %found, label %search_continue
search_continue:
  %i_next = add i64 %i, 1
  br label %search_loop
found:
  ; Value is at offset 2 + i*2 + 1
  %val_idx = add i64 %key_idx, 1
  %val_ptr = getelementptr i64, i64* %obj, i64 %val_idx
  %value = load i64, i64* %val_ptr
  ret i64 %value
not_found:
  ; Return undefined
  ret i64 9221120237041090561
}

; ============================================================
; Function: parseArgs
; ============================================================
define i64 @parseArgs(i64 %p0) {
entry:
  %local0 = alloca i64
  %local1 = alloca i64
  %local2 = alloca i64
  %local3 = alloca i64
  store i64 %p0, i64* %local0
  br label %parseArgs_entry
parseArgs_entry:
  %r1 = add i64 0, 8
  %r0 = call i64 @tscl_alloc_object(i64 %r1)
  %r3 = getelementptr [4 x i8], [4 x i8]* @.str.0, i64 0, i64 0
  %r4 = ptrtoint i8* %r3 to i64
  %r5 = and i64 %r4, 281474976710655
  %r2 = or i64 %r5, 18445618173802708992
  %r6 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r7 = ptrtoint i8* %r6 to i64
  %r8 = and i64 %r7, 281474976710655
  %r9 = or i64 %r8, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r9, i64 %r2)
  %r11 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r12 = ptrtoint i8* %r11 to i64
  %r13 = and i64 %r12, 281474976710655
  %r10 = or i64 %r13, 18445618173802708992
  %r14 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r15 = ptrtoint i8* %r14 to i64
  %r16 = and i64 %r15, 281474976710655
  %r17 = or i64 %r16, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r17, i64 %r10)
  %r19 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r20 = ptrtoint i8* %r19 to i64
  %r21 = and i64 %r20, 281474976710655
  %r18 = or i64 %r21, 18445618173802708992
  %r22 = getelementptr [11 x i8], [11 x i8]* @.str.4, i64 0, i64 0
  %r23 = ptrtoint i8* %r22 to i64
  %r24 = and i64 %r23, 281474976710655
  %r25 = or i64 %r24, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r25, i64 %r18)
  %r26 = add i64 0, 9221120237041090560
  %r27 = getelementptr [7 x i8], [7 x i8]* @.str.5, i64 0, i64 0
  %r28 = ptrtoint i8* %r27 to i64
  %r29 = and i64 %r28, 281474976710655
  %r30 = or i64 %r29, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r30, i64 %r26)
  %r31 = add i64 0, 9221120237041090560
  %r32 = getelementptr [8 x i8], [8 x i8]* @.str.6, i64 0, i64 0
  %r33 = ptrtoint i8* %r32 to i64
  %r34 = and i64 %r33, 281474976710655
  %r35 = or i64 %r34, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r35, i64 %r31)
  %r36 = add i64 0, 9221120237041090560
  %r37 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r38 = ptrtoint i8* %r37 to i64
  %r39 = and i64 %r38, 281474976710655
  %r40 = or i64 %r39, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r40, i64 %r36)
  store i64 %r0, i64* %local1
  %r42 = call i64 @tscl_box_number(double 0.0)
  store i64 %r42, i64* %local2
  br label %while_cond_0
while_cond_0:
  %r43 = load i64, i64* %local2
  %r44 = load i64, i64* %local0
  %r45 = call i64 @tscl_array_length(i64 %r44)
  %r46 = call i64 @tscl_lt_any(i64 %r43, i64 %r45)
  %r47 = and i64 %r46, 1
  %r48 = icmp ne i64 %r47, 0
  br i1 %r48, label %while_body_1, label %while_exit_2
while_body_1:
  %r49 = load i64, i64* %local0
  %r50 = load i64, i64* %local2
  %r51 = call i64 @tscl_array_get(i64 %r49, i64 %r50)
  store i64 %r51, i64* %local3
  %r52 = load i64, i64* %local3
  %r54 = getelementptr [4 x i8], [4 x i8]* @.str.0, i64 0, i64 0
  %r55 = ptrtoint i8* %r54 to i64
  %r56 = and i64 %r55, 281474976710655
  %r53 = or i64 %r56, 18445618173802708992
  %r57 = call i64 @tscl_eq_any(i64 %r52, i64 %r53)
  %r58 = load i64, i64* %local3
  %r60 = getelementptr [6 x i8], [6 x i8]* @.str.8, i64 0, i64 0
  %r61 = ptrtoint i8* %r60 to i64
  %r62 = and i64 %r61, 281474976710655
  %r59 = or i64 %r62, 18445618173802708992
  %r63 = call i64 @tscl_eq_any(i64 %r58, i64 %r59)
  %r64 = or i64 %r57, %r63
  %r65 = load i64, i64* %local3
  %r67 = getelementptr [3 x i8], [3 x i8]* @.str.9, i64 0, i64 0
  %r68 = ptrtoint i8* %r67 to i64
  %r69 = and i64 %r68, 281474976710655
  %r66 = or i64 %r69, 18445618173802708992
  %r70 = call i64 @tscl_eq_any(i64 %r65, i64 %r66)
  %r71 = or i64 %r64, %r70
  %r72 = load i64, i64* %local3
  %r74 = getelementptr [4 x i8], [4 x i8]* @.str.10, i64 0, i64 0
  %r75 = ptrtoint i8* %r74 to i64
  %r76 = and i64 %r75, 281474976710655
  %r73 = or i64 %r76, 18445618173802708992
  %r77 = call i64 @tscl_eq_any(i64 %r72, i64 %r73)
  %r78 = or i64 %r71, %r77
  %r79 = load i64, i64* %local3
  %r81 = getelementptr [6 x i8], [6 x i8]* @.str.11, i64 0, i64 0
  %r82 = ptrtoint i8* %r81 to i64
  %r83 = and i64 %r82, 281474976710655
  %r80 = or i64 %r83, 18445618173802708992
  %r84 = call i64 @tscl_eq_any(i64 %r79, i64 %r80)
  %r85 = or i64 %r78, %r84
  %r86 = load i64, i64* %local3
  %r88 = getelementptr [5 x i8], [5 x i8]* @.str.12, i64 0, i64 0
  %r89 = ptrtoint i8* %r88 to i64
  %r90 = and i64 %r89, 281474976710655
  %r87 = or i64 %r90, 18445618173802708992
  %r91 = call i64 @tscl_eq_any(i64 %r86, i64 %r87)
  %r92 = or i64 %r85, %r91
  %r93 = and i64 %r92, 1
  %r94 = icmp ne i64 %r93, 0
  br i1 %r94, label %if_then_3, label %if_else_4
while_exit_2:
  %r95 = load i64, i64* %local1
  ret i64 %r95
if_then_3:
  %r96 = load i64, i64* %local3
  %r97 = load i64, i64* %local1
  %r98 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r99 = ptrtoint i8* %r98 to i64
  %r100 = and i64 %r99, 281474976710655
  %r101 = or i64 %r100, 18445618173802708992
  call void @tscl_object_set(i64 %r97, i64 %r101, i64 %r96)
  br label %if_merge_5
if_else_4:
  %r102 = load i64, i64* %local3
  %r104 = getelementptr [3 x i8], [3 x i8]* @.str.13, i64 0, i64 0
  %r105 = ptrtoint i8* %r104 to i64
  %r106 = and i64 %r105, 281474976710655
  %r103 = or i64 %r106, 18445618173802708992
  %r107 = call i64 @tscl_eq_any(i64 %r102, i64 %r103)
  %r108 = load i64, i64* %local3
  %r110 = getelementptr [9 x i8], [9 x i8]* @.str.14, i64 0, i64 0
  %r111 = ptrtoint i8* %r110 to i64
  %r112 = and i64 %r111, 281474976710655
  %r109 = or i64 %r112, 18445618173802708992
  %r113 = call i64 @tscl_eq_any(i64 %r108, i64 %r109)
  %r114 = or i64 %r107, %r113
  %r115 = and i64 %r114, 1
  %r116 = icmp ne i64 %r115, 0
  br i1 %r116, label %if_then_6, label %if_else_7
if_merge_5:
  %r117 = load i64, i64* %local2
  %r119 = call i64 @tscl_box_number(double 1.0)
  %r120 = call i64 @tscl_add_any(i64 %r117, i64 %r119)
  store i64 %r120, i64* %local2
  br label %while_cond_0
if_then_6:
  %r121 = load i64, i64* %local2
  %r123 = call i64 @tscl_box_number(double 1.0)
  %r124 = call i64 @tscl_add_any(i64 %r121, i64 %r123)
  store i64 %r124, i64* %local2
  %r125 = load i64, i64* %local2
  %r126 = load i64, i64* %local0
  %r127 = call i64 @tscl_array_length(i64 %r126)
  %r128 = call i64 @tscl_lt_any(i64 %r125, i64 %r127)
  %r129 = and i64 %r128, 1
  %r130 = icmp ne i64 %r129, 0
  br i1 %r130, label %if_then_9, label %if_else_10
if_else_7:
  %r131 = load i64, i64* %local3
  %r133 = getelementptr [10 x i8], [10 x i8]* @.str.15, i64 0, i64 0
  %r134 = ptrtoint i8* %r133 to i64
  %r135 = and i64 %r134, 281474976710655
  %r132 = or i64 %r135, 18445618173802708992
  %r136 = call i64 @tscl_eq_any(i64 %r131, i64 %r132)
  %r137 = and i64 %r136, 1
  %r138 = icmp ne i64 %r137, 0
  br i1 %r138, label %if_then_12, label %if_else_13
if_merge_8:
  br label %if_merge_5
if_then_9:
  %r139 = load i64, i64* %local0
  %r140 = load i64, i64* %local2
  %r141 = call i64 @tscl_array_get(i64 %r139, i64 %r140)
  %r142 = load i64, i64* %local1
  %r143 = getelementptr [11 x i8], [11 x i8]* @.str.4, i64 0, i64 0
  %r144 = ptrtoint i8* %r143 to i64
  %r145 = and i64 %r144, 281474976710655
  %r146 = or i64 %r145, 18445618173802708992
  call void @tscl_object_set(i64 %r142, i64 %r146, i64 %r141)
  br label %if_merge_11
if_else_10:
  br label %if_merge_11
if_merge_11:
  br label %if_merge_8
if_then_12:
  %r147 = add i64 0, 9221120237041090561
  %r148 = load i64, i64* %local1
  %r149 = getelementptr [7 x i8], [7 x i8]* @.str.5, i64 0, i64 0
  %r150 = ptrtoint i8* %r149 to i64
  %r151 = and i64 %r150, 281474976710655
  %r152 = or i64 %r151, 18445618173802708992
  call void @tscl_object_set(i64 %r148, i64 %r152, i64 %r147)
  br label %if_merge_14
if_else_13:
  %r153 = load i64, i64* %local3
  %r155 = getelementptr [11 x i8], [11 x i8]* @.str.16, i64 0, i64 0
  %r156 = ptrtoint i8* %r155 to i64
  %r157 = and i64 %r156, 281474976710655
  %r154 = or i64 %r157, 18445618173802708992
  %r158 = call i64 @tscl_eq_any(i64 %r153, i64 %r154)
  %r159 = and i64 %r158, 1
  %r160 = icmp ne i64 %r159, 0
  br i1 %r160, label %if_then_15, label %if_else_16
if_merge_14:
  br label %if_merge_8
if_then_15:
  %r161 = add i64 0, 9221120237041090561
  %r162 = load i64, i64* %local1
  %r163 = getelementptr [8 x i8], [8 x i8]* @.str.6, i64 0, i64 0
  %r164 = ptrtoint i8* %r163 to i64
  %r165 = and i64 %r164, 281474976710655
  %r166 = or i64 %r165, 18445618173802708992
  call void @tscl_object_set(i64 %r162, i64 %r166, i64 %r161)
  br label %if_merge_17
if_else_16:
  %r167 = load i64, i64* %local3
  %r169 = getelementptr [3 x i8], [3 x i8]* @.str.17, i64 0, i64 0
  %r170 = ptrtoint i8* %r169 to i64
  %r171 = and i64 %r170, 281474976710655
  %r168 = or i64 %r171, 18445618173802708992
  %r172 = call i64 @tscl_eq_any(i64 %r167, i64 %r168)
  %r173 = load i64, i64* %local3
  %r175 = getelementptr [10 x i8], [10 x i8]* @.str.18, i64 0, i64 0
  %r176 = ptrtoint i8* %r175 to i64
  %r177 = and i64 %r176, 281474976710655
  %r174 = or i64 %r177, 18445618173802708992
  %r178 = call i64 @tscl_eq_any(i64 %r173, i64 %r174)
  %r179 = or i64 %r172, %r178
  %r180 = and i64 %r179, 1
  %r181 = icmp ne i64 %r180, 0
  br i1 %r181, label %if_then_18, label %if_else_19
if_merge_17:
  br label %if_merge_14
if_then_18:
  %r182 = add i64 0, 9221120237041090561
  %r183 = load i64, i64* %local1
  %r184 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r185 = ptrtoint i8* %r184 to i64
  %r186 = and i64 %r185, 281474976710655
  %r187 = or i64 %r186, 18445618173802708992
  call void @tscl_object_set(i64 %r183, i64 %r187, i64 %r182)
  br label %if_merge_20
if_else_19:
  %r188 = load i64, i64* %local3
  %r190 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r191 = ptrtoint i8* %r190 to i64
  %r192 = and i64 %r191, 281474976710655
  %r189 = or i64 %r192, 18445618173802708992
  %r193 = call i64 @tscl_ne_any(i64 %r188, i64 %r189)
  %r194 = and i64 %r193, 1
  %r195 = icmp ne i64 %r194, 0
  br i1 %r195, label %if_then_21, label %if_else_22
if_merge_20:
  br label %if_merge_17
if_then_21:
  %r196 = load i64, i64* %local3
  %r197 = load i64, i64* %local1
  %r198 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r199 = ptrtoint i8* %r198 to i64
  %r200 = and i64 %r199, 281474976710655
  %r201 = or i64 %r200, 18445618173802708992
  call void @tscl_object_set(i64 %r197, i64 %r201, i64 %r196)
  br label %if_merge_23
if_else_22:
  br label %if_merge_23
if_merge_23:
  br label %if_merge_20
}

; ============================================================
; Function: printUsage
; ============================================================
define i64 @printUsage() {
entry:
  br label %printUsage_entry
printUsage_entry:
  %r1 = getelementptr [27 x i8], [27 x i8]* @.str.19, i64 0, i64 0
  %r2 = ptrtoint i8* %r1 to i64
  %r3 = and i64 %r2, 281474976710655
  %r0 = or i64 %r3, 18445618173802708992
  %r4 = call i64 @tscl_console_log(i64 %r0)
  %r6 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r7 = ptrtoint i8* %r6 to i64
  %r8 = and i64 %r7, 281474976710655
  %r5 = or i64 %r8, 18445618173802708992
  %r9 = call i64 @tscl_console_log(i64 %r5)
  %r11 = getelementptr [40 x i8], [40 x i8]* @.str.20, i64 0, i64 0
  %r12 = ptrtoint i8* %r11 to i64
  %r13 = and i64 %r12, 281474976710655
  %r10 = or i64 %r13, 18445618173802708992
  %r14 = call i64 @tscl_console_log(i64 %r10)
  %r16 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r17 = ptrtoint i8* %r16 to i64
  %r18 = and i64 %r17, 281474976710655
  %r15 = or i64 %r18, 18445618173802708992
  %r19 = call i64 @tscl_console_log(i64 %r15)
  %r21 = getelementptr [10 x i8], [10 x i8]* @.str.21, i64 0, i64 0
  %r22 = ptrtoint i8* %r21 to i64
  %r23 = and i64 %r22, 281474976710655
  %r20 = or i64 %r23, 18445618173802708992
  %r24 = call i64 @tscl_console_log(i64 %r20)
  %r26 = getelementptr [31 x i8], [31 x i8]* @.str.22, i64 0, i64 0
  %r27 = ptrtoint i8* %r26 to i64
  %r28 = and i64 %r27, 281474976710655
  %r25 = or i64 %r28, 18445618173802708992
  %r29 = call i64 @tscl_console_log(i64 %r25)
  %r31 = getelementptr [38 x i8], [38 x i8]* @.str.23, i64 0, i64 0
  %r32 = ptrtoint i8* %r31 to i64
  %r33 = and i64 %r32, 281474976710655
  %r30 = or i64 %r33, 18445618173802708992
  %r34 = call i64 @tscl_console_log(i64 %r30)
  %r36 = getelementptr [46 x i8], [46 x i8]* @.str.24, i64 0, i64 0
  %r37 = ptrtoint i8* %r36 to i64
  %r38 = and i64 %r37, 281474976710655
  %r35 = or i64 %r38, 18445618173802708992
  %r39 = call i64 @tscl_console_log(i64 %r35)
  %r41 = getelementptr [46 x i8], [46 x i8]* @.str.25, i64 0, i64 0
  %r42 = ptrtoint i8* %r41 to i64
  %r43 = and i64 %r42, 281474976710655
  %r40 = or i64 %r43, 18445618173802708992
  %r44 = call i64 @tscl_console_log(i64 %r40)
  %r46 = getelementptr [33 x i8], [33 x i8]* @.str.26, i64 0, i64 0
  %r47 = ptrtoint i8* %r46 to i64
  %r48 = and i64 %r47, 281474976710655
  %r45 = or i64 %r48, 18445618173802708992
  %r49 = call i64 @tscl_console_log(i64 %r45)
  %r51 = getelementptr [29 x i8], [29 x i8]* @.str.27, i64 0, i64 0
  %r52 = ptrtoint i8* %r51 to i64
  %r53 = and i64 %r52, 281474976710655
  %r50 = or i64 %r53, 18445618173802708992
  %r54 = call i64 @tscl_console_log(i64 %r50)
  %r56 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r57 = ptrtoint i8* %r56 to i64
  %r58 = and i64 %r57, 281474976710655
  %r55 = or i64 %r58, 18445618173802708992
  %r59 = call i64 @tscl_console_log(i64 %r55)
  %r61 = getelementptr [9 x i8], [9 x i8]* @.str.28, i64 0, i64 0
  %r62 = ptrtoint i8* %r61 to i64
  %r63 = and i64 %r62, 281474976710655
  %r60 = or i64 %r63, 18445618173802708992
  %r64 = call i64 @tscl_console_log(i64 %r60)
  %r66 = getelementptr [30 x i8], [30 x i8]* @.str.29, i64 0, i64 0
  %r67 = ptrtoint i8* %r66 to i64
  %r68 = and i64 %r67, 281474976710655
  %r65 = or i64 %r68, 18445618173802708992
  %r69 = call i64 @tscl_console_log(i64 %r65)
  %r71 = getelementptr [34 x i8], [34 x i8]* @.str.30, i64 0, i64 0
  %r72 = ptrtoint i8* %r71 to i64
  %r73 = and i64 %r72, 281474976710655
  %r70 = or i64 %r73, 18445618173802708992
  %r74 = call i64 @tscl_console_log(i64 %r70)
  %r76 = getelementptr [35 x i8], [35 x i8]* @.str.31, i64 0, i64 0
  %r77 = ptrtoint i8* %r76 to i64
  %r78 = and i64 %r77, 281474976710655
  %r75 = or i64 %r78, 18445618173802708992
  %r79 = call i64 @tscl_console_log(i64 %r75)
  %r81 = getelementptr [33 x i8], [33 x i8]* @.str.32, i64 0, i64 0
  %r82 = ptrtoint i8* %r81 to i64
  %r83 = and i64 %r82, 281474976710655
  %r80 = or i64 %r83, 18445618173802708992
  %r84 = call i64 @tscl_console_log(i64 %r80)
  %r86 = getelementptr [33 x i8], [33 x i8]* @.str.33, i64 0, i64 0
  %r87 = ptrtoint i8* %r86 to i64
  %r88 = and i64 %r87, 281474976710655
  %r85 = or i64 %r88, 18445618173802708992
  %r89 = call i64 @tscl_console_log(i64 %r85)
  ret i64 9221120237041090561
}

; ============================================================
; Function: logVerbose
; ============================================================
define i64 @logVerbose(i64 %p0, i64 %p1) {
entry:
  %local0 = alloca i64
  %local1 = alloca i64
  store i64 %p0, i64* %local0
  store i64 %p1, i64* %local1
  br label %logVerbose_entry
logVerbose_entry:
  %r0 = load i64, i64* %local0
  %r1 = and i64 %r0, 1
  %r2 = icmp ne i64 %r1, 0
  br i1 %r2, label %if_then_0, label %if_else_1
if_then_0:
  %r3 = load i64, i64* %local1
  %r4 = call i64 @tscl_console_log(i64 %r3)
  br label %if_merge_2
if_else_1:
  br label %if_merge_2
if_merge_2:
  ret i64 9221120237041090561
}

; ============================================================
; Function: compileSource
; ============================================================
define i64 @compileSource(i64 %p0, i64 %p1) {
entry:
  %local0 = alloca i64
  %local1 = alloca i64
  %local2 = alloca i64
  %local3 = alloca i64
  %local4 = alloca i64
  store i64 %p0, i64* %local0
  store i64 %p1, i64* %local1
  br label %compileSource_entry
compileSource_entry:
  %r0 = load i64, i64* %local1
  %r2 = getelementptr [14 x i8], [14 x i8]* @.str.34, i64 0, i64 0
  %r3 = ptrtoint i8* %r2 to i64
  %r4 = and i64 %r3, 281474976710655
  %r1 = or i64 %r4, 18445618173802708992
  %r5 = call i64 @logVerbose(i64 %r0, i64 %r1)
  %r6 = load i64, i64* %local0
  %r7 = call i64 @tokenize(i64 %r6)
  store i64 %r7, i64* %local2
  %r8 = load i64, i64* %local1
  %r10 = getelementptr [3 x i8], [3 x i8]* @.str.35, i64 0, i64 0
  %r11 = ptrtoint i8* %r10 to i64
  %r12 = and i64 %r11, 281474976710655
  %r9 = or i64 %r12, 18445618173802708992
  %r13 = load i64, i64* %local2
  %r14 = call i64 @tscl_array_length(i64 %r13)
  %r15 = call i64 @tscl_add_any(i64 %r9, i64 %r14)
  %r17 = getelementptr [8 x i8], [8 x i8]* @.str.36, i64 0, i64 0
  %r18 = ptrtoint i8* %r17 to i64
  %r19 = and i64 %r18, 281474976710655
  %r16 = or i64 %r19, 18445618173802708992
  %r20 = call i64 @tscl_add_any(i64 %r15, i64 %r16)
  %r21 = call i64 @logVerbose(i64 %r8, i64 %r20)
  %r22 = load i64, i64* %local1
  %r24 = getelementptr [11 x i8], [11 x i8]* @.str.37, i64 0, i64 0
  %r25 = ptrtoint i8* %r24 to i64
  %r26 = and i64 %r25, 281474976710655
  %r23 = or i64 %r26, 18445618173802708992
  %r27 = call i64 @logVerbose(i64 %r22, i64 %r23)
  %r28 = load i64, i64* %local0
  %r29 = call i64 @parseSource(i64 %r28)
  store i64 %r29, i64* %local3
  %r30 = load i64, i64* %local3
  %r31 = add i64 0, 9221120237041090561
  %r32 = call i64 @tscl_eq_any(i64 %r30, i64 %r31)
  %r33 = and i64 %r32, 1
  %r34 = icmp ne i64 %r33, 0
  br i1 %r34, label %if_then_0, label %if_else_1
if_then_0:
  %r36 = getelementptr [12 x i8], [12 x i8]* @.str.38, i64 0, i64 0
  %r37 = ptrtoint i8* %r36 to i64
  %r38 = and i64 %r37, 281474976710655
  %r35 = or i64 %r38, 18445618173802708992
  %r39 = call i64 @tscl_console_log(i64 %r35)
  %r40 = add i64 0, 9221120237041090561
  ret i64 %r40
if_else_1:
  br label %if_merge_2
if_merge_2:
  %r41 = load i64, i64* %local1
  %r43 = getelementptr [3 x i8], [3 x i8]* @.str.35, i64 0, i64 0
  %r44 = ptrtoint i8* %r43 to i64
  %r45 = and i64 %r44, 281474976710655
  %r42 = or i64 %r45, 18445618173802708992
  %r46 = load i64, i64* %local3
  %r48 = getelementptr [5 x i8], [5 x i8]* @.str.39, i64 0, i64 0
  %r49 = ptrtoint i8* %r48 to i64
  %r50 = and i64 %r49, 281474976710655
  %r51 = or i64 %r50, 18445618173802708992
  %r47 = call i64 @tscl_object_get(i64 %r46, i64 %r51)
  %r52 = call i64 @tscl_array_length(i64 %r47)
  %r53 = call i64 @tscl_add_any(i64 %r42, i64 %r52)
  %r55 = getelementptr [12 x i8], [12 x i8]* @.str.40, i64 0, i64 0
  %r56 = ptrtoint i8* %r55 to i64
  %r57 = and i64 %r56, 281474976710655
  %r54 = or i64 %r57, 18445618173802708992
  %r58 = call i64 @tscl_add_any(i64 %r53, i64 %r54)
  %r59 = call i64 @logVerbose(i64 %r41, i64 %r58)
  %r60 = load i64, i64* %local1
  %r62 = getelementptr [18 x i8], [18 x i8]* @.str.41, i64 0, i64 0
  %r63 = ptrtoint i8* %r62 to i64
  %r64 = and i64 %r63, 281474976710655
  %r61 = or i64 %r64, 18445618173802708992
  %r65 = call i64 @logVerbose(i64 %r60, i64 %r61)
  %r66 = load i64, i64* %local3
  %r67 = call i64 @lowerProgramToIr(i64 %r66)
  store i64 %r67, i64* %local4
  %r68 = load i64, i64* %local4
  %r69 = add i64 0, 9221120237041090561
  %r70 = call i64 @tscl_eq_any(i64 %r68, i64 %r69)
  %r71 = and i64 %r70, 1
  %r72 = icmp ne i64 %r71, 0
  br i1 %r72, label %if_then_3, label %if_else_4
if_then_3:
  %r74 = getelementptr [18 x i8], [18 x i8]* @.str.42, i64 0, i64 0
  %r75 = ptrtoint i8* %r74 to i64
  %r76 = and i64 %r75, 281474976710655
  %r73 = or i64 %r76, 18445618173802708992
  %r77 = call i64 @tscl_console_log(i64 %r73)
  %r78 = add i64 0, 9221120237041090561
  ret i64 %r78
if_else_4:
  br label %if_merge_5
if_merge_5:
  %r79 = load i64, i64* %local1
  %r81 = getelementptr [3 x i8], [3 x i8]* @.str.35, i64 0, i64 0
  %r82 = ptrtoint i8* %r81 to i64
  %r83 = and i64 %r82, 281474976710655
  %r80 = or i64 %r83, 18445618173802708992
  %r84 = load i64, i64* %local4
  %r86 = getelementptr [10 x i8], [10 x i8]* @.str.43, i64 0, i64 0
  %r87 = ptrtoint i8* %r86 to i64
  %r88 = and i64 %r87, 281474976710655
  %r89 = or i64 %r88, 18445618173802708992
  %r85 = call i64 @tscl_object_get(i64 %r84, i64 %r89)
  %r90 = call i64 @tscl_array_length(i64 %r85)
  %r91 = call i64 @tscl_add_any(i64 %r80, i64 %r90)
  %r93 = getelementptr [11 x i8], [11 x i8]* @.str.44, i64 0, i64 0
  %r94 = ptrtoint i8* %r93 to i64
  %r95 = and i64 %r94, 281474976710655
  %r92 = or i64 %r95, 18445618173802708992
  %r96 = call i64 @tscl_add_any(i64 %r91, i64 %r92)
  %r97 = call i64 @logVerbose(i64 %r79, i64 %r96)
  %r98 = load i64, i64* %local1
  %r100 = getelementptr [16 x i8], [16 x i8]* @.str.45, i64 0, i64 0
  %r101 = ptrtoint i8* %r100 to i64
  %r102 = and i64 %r101, 281474976710655
  %r99 = or i64 %r102, 18445618173802708992
  %r103 = call i64 @logVerbose(i64 %r98, i64 %r99)
  %r104 = load i64, i64* %local4
  %r105 = call i64 @verifyIrModule(i64 %r104)
  %r107 = and i64 %r105, 1
  %r108 = icmp eq i64 %r107, 0
  %r106 = select i1 %r108, i64 9221120237041090561, i64 9221120237041090560
  %r109 = and i64 %r106, 1
  %r110 = icmp ne i64 %r109, 0
  br i1 %r110, label %if_then_6, label %if_else_7
if_then_6:
  %r112 = getelementptr [23 x i8], [23 x i8]* @.str.46, i64 0, i64 0
  %r113 = ptrtoint i8* %r112 to i64
  %r114 = and i64 %r113, 281474976710655
  %r111 = or i64 %r114, 18445618173802708992
  %r115 = call i64 @tscl_console_log(i64 %r111)
  %r116 = add i64 0, 9221120237041090561
  ret i64 %r116
if_else_7:
  br label %if_merge_8
if_merge_8:
  %r117 = load i64, i64* %local1
  %r119 = getelementptr [21 x i8], [21 x i8]* @.str.47, i64 0, i64 0
  %r120 = ptrtoint i8* %r119 to i64
  %r121 = and i64 %r120, 281474976710655
  %r118 = or i64 %r121, 18445618173802708992
  %r122 = call i64 @logVerbose(i64 %r117, i64 %r118)
  %r123 = load i64, i64* %local4
  ret i64 %r123
}

; ============================================================
; Function: script_main
; ============================================================
define i64 @script_main(i64 %p0) {
entry:
  %local0 = alloca i64
  %local1 = alloca i64
  %local2 = alloca i64
  %local3 = alloca i64
  %local4 = alloca i64
  %local5 = alloca i64
  %local6 = alloca i64
  %local7 = alloca i64
  %local8 = alloca i64
  %local9 = alloca i64
  %local10 = alloca i64
  %local11 = alloca i64
  %local12 = alloca i64
  %local13 = alloca i64
  %local14 = alloca i64
  %local15 = alloca i64
  %local16 = alloca i64
  %local17 = alloca i64
  store i64 %p0, i64* %local0
  br label %main_entry
main_entry:
  %r0 = load i64, i64* %local0
  %r1 = call i64 @tscl_array_length(i64 %r0)
  %r3 = call i64 @tscl_box_number(double 2.0)
  %r4 = call i64 @tscl_lt_any(i64 %r1, i64 %r3)
  %r5 = and i64 %r4, 1
  %r6 = icmp ne i64 %r5, 0
  br i1 %r6, label %if_then_0, label %if_else_1
if_then_0:
  %r7 = call i64 @printUsage()
  ret i64 9221120237041090561
if_else_1:
  br label %if_merge_2
if_merge_2:
  %r8 = load i64, i64* %local0
  %r9 = call i64 @parseArgs(i64 %r8)
  store i64 %r9, i64* %local1
  %r10 = load i64, i64* %local1
  %r12 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r13 = ptrtoint i8* %r12 to i64
  %r14 = and i64 %r13, 281474976710655
  %r15 = or i64 %r14, 18445618173802708992
  %r11 = call i64 @tscl_object_get(i64 %r10, i64 %r15)
  %r17 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r18 = ptrtoint i8* %r17 to i64
  %r19 = and i64 %r18, 281474976710655
  %r16 = or i64 %r19, 18445618173802708992
  %r20 = call i64 @tscl_eq_any(i64 %r11, i64 %r16)
  %r21 = and i64 %r20, 1
  %r22 = icmp ne i64 %r21, 0
  br i1 %r22, label %if_then_3, label %if_else_4
if_then_3:
  %r24 = getelementptr [31 x i8], [31 x i8]* @.str.48, i64 0, i64 0
  %r25 = ptrtoint i8* %r24 to i64
  %r26 = and i64 %r25, 281474976710655
  %r23 = or i64 %r26, 18445618173802708992
  %r27 = call i64 @tscl_console_log(i64 %r23)
  ret i64 9221120237041090561
if_else_4:
  br label %if_merge_5
if_merge_5:
  %r28 = load i64, i64* %local1
  %r30 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r31 = ptrtoint i8* %r30 to i64
  %r32 = and i64 %r31, 281474976710655
  %r33 = or i64 %r32, 18445618173802708992
  %r29 = call i64 @tscl_object_get(i64 %r28, i64 %r33)
  %r35 = getelementptr [3 x i8], [3 x i8]* @.str.49, i64 0, i64 0
  %r36 = ptrtoint i8* %r35 to i64
  %r37 = and i64 %r36, 281474976710655
  %r34 = or i64 %r37, 18445618173802708992
  %r39 = getelementptr [11 x i8], [11 x i8]* @.str.50, i64 0, i64 0
  %r40 = ptrtoint i8* %r39 to i64
  %r41 = and i64 %r40, 281474976710655
  %r42 = or i64 %r41, 18445618173802708992
  %r38 = call i64 @tscl_object_get(i64 %r34, i64 %r42)
  %r43 = call i64 %r38(i64 %r29)
  %r45 = and i64 %r43, 1
  %r46 = icmp eq i64 %r45, 0
  %r44 = select i1 %r46, i64 9221120237041090561, i64 9221120237041090560
  %r47 = and i64 %r44, 1
  %r48 = icmp ne i64 %r47, 0
  br i1 %r48, label %if_then_6, label %if_else_7
if_then_6:
  %r50 = getelementptr [24 x i8], [24 x i8]* @.str.51, i64 0, i64 0
  %r51 = ptrtoint i8* %r50 to i64
  %r52 = and i64 %r51, 281474976710655
  %r49 = or i64 %r52, 18445618173802708992
  %r53 = load i64, i64* %local1
  %r55 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r56 = ptrtoint i8* %r55 to i64
  %r57 = and i64 %r56, 281474976710655
  %r58 = or i64 %r57, 18445618173802708992
  %r54 = call i64 @tscl_object_get(i64 %r53, i64 %r58)
  %r59 = call i64 @tscl_add_any(i64 %r49, i64 %r54)
  %r60 = call i64 @tscl_console_log(i64 %r59)
  ret i64 9221120237041090561
if_else_7:
  br label %if_merge_8
if_merge_8:
  %r61 = load i64, i64* %local1
  %r63 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r64 = ptrtoint i8* %r63 to i64
  %r65 = and i64 %r64, 281474976710655
  %r66 = or i64 %r65, 18445618173802708992
  %r62 = call i64 @tscl_object_get(i64 %r61, i64 %r66)
  %r68 = getelementptr [5 x i8], [5 x i8]* @.str.52, i64 0, i64 0
  %r69 = ptrtoint i8* %r68 to i64
  %r70 = and i64 %r69, 281474976710655
  %r67 = or i64 %r70, 18445618173802708992
  %r72 = getelementptr [3 x i8], [3 x i8]* @.str.49, i64 0, i64 0
  %r73 = ptrtoint i8* %r72 to i64
  %r74 = and i64 %r73, 281474976710655
  %r71 = or i64 %r74, 18445618173802708992
  %r76 = getelementptr [13 x i8], [13 x i8]* @.str.53, i64 0, i64 0
  %r77 = ptrtoint i8* %r76 to i64
  %r78 = and i64 %r77, 281474976710655
  %r79 = or i64 %r78, 18445618173802708992
  %r75 = call i64 @tscl_object_get(i64 %r71, i64 %r79)
  %r80 = call i64 %r75(i64 %r62, i64 %r67)
  store i64 %r80, i64* %local2
  %r81 = load i64, i64* %local1
  %r83 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r84 = ptrtoint i8* %r83 to i64
  %r85 = and i64 %r84, 281474976710655
  %r86 = or i64 %r85, 18445618173802708992
  %r82 = call i64 @tscl_object_get(i64 %r81, i64 %r86)
  %r88 = getelementptr [4 x i8], [4 x i8]* @.str.10, i64 0, i64 0
  %r89 = ptrtoint i8* %r88 to i64
  %r90 = and i64 %r89, 281474976710655
  %r87 = or i64 %r90, 18445618173802708992
  %r91 = call i64 @tscl_eq_any(i64 %r82, i64 %r87)
  %r92 = and i64 %r91, 1
  %r93 = icmp ne i64 %r92, 0
  br i1 %r93, label %if_then_9, label %if_else_10
if_then_9:
  %r94 = load i64, i64* %local2
  %r95 = call i64 @parseSource(i64 %r94)
  store i64 %r95, i64* %local3
  %r96 = load i64, i64* %local3
  %r97 = add i64 0, 9221120237041090561
  %r98 = call i64 @tscl_ne_any(i64 %r96, i64 %r97)
  %r99 = and i64 %r98, 1
  %r100 = icmp ne i64 %r99, 0
  br i1 %r100, label %if_then_12, label %if_else_13
if_else_10:
  br label %if_merge_11
if_merge_11:
  %r101 = load i64, i64* %local1
  %r103 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r104 = ptrtoint i8* %r103 to i64
  %r105 = and i64 %r104, 281474976710655
  %r106 = or i64 %r105, 18445618173802708992
  %r102 = call i64 @tscl_object_get(i64 %r101, i64 %r106)
  %r108 = getelementptr [6 x i8], [6 x i8]* @.str.11, i64 0, i64 0
  %r109 = ptrtoint i8* %r108 to i64
  %r110 = and i64 %r109, 281474976710655
  %r107 = or i64 %r110, 18445618173802708992
  %r111 = call i64 @tscl_eq_any(i64 %r102, i64 %r107)
  %r112 = and i64 %r111, 1
  %r113 = icmp ne i64 %r112, 0
  br i1 %r113, label %if_then_15, label %if_else_16
if_then_12:
  %r114 = load i64, i64* %local3
  %r115 = add i64 0, 9221120237041090561
  %r117 = call i64 @tscl_box_number(double 2.0)
  %r119 = getelementptr [5 x i8], [5 x i8]* @.str.54, i64 0, i64 0
  %r120 = ptrtoint i8* %r119 to i64
  %r121 = and i64 %r120, 281474976710655
  %r118 = or i64 %r121, 18445618173802708992
  %r123 = getelementptr [10 x i8], [10 x i8]* @.str.55, i64 0, i64 0
  %r124 = ptrtoint i8* %r123 to i64
  %r125 = and i64 %r124, 281474976710655
  %r126 = or i64 %r125, 18445618173802708992
  %r122 = call i64 @tscl_object_get(i64 %r118, i64 %r126)
  %r127 = call i64 %r122(i64 %r114, i64 %r115, i64 %r117)
  %r128 = call i64 @tscl_console_log(i64 %r127)
  br label %if_merge_14
if_else_13:
  br label %if_merge_14
if_merge_14:
  ret i64 9221120237041090561
if_then_15:
  %r129 = load i64, i64* %local1
  %r131 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r132 = ptrtoint i8* %r131 to i64
  %r133 = and i64 %r132, 281474976710655
  %r134 = or i64 %r133, 18445618173802708992
  %r130 = call i64 @tscl_object_get(i64 %r129, i64 %r134)
  %r136 = getelementptr [19 x i8], [19 x i8]* @.str.56, i64 0, i64 0
  %r137 = ptrtoint i8* %r136 to i64
  %r138 = and i64 %r137, 281474976710655
  %r135 = or i64 %r138, 18445618173802708992
  %r139 = call i64 @logVerbose(i64 %r130, i64 %r135)
  %r140 = load i64, i64* %local2
  %r141 = call i64 @parseSource(i64 %r140)
  store i64 %r141, i64* %local4
  %r142 = load i64, i64* %local4
  %r143 = add i64 0, 9221120237041090561
  %r144 = call i64 @tscl_eq_any(i64 %r142, i64 %r143)
  %r145 = and i64 %r144, 1
  %r146 = icmp ne i64 %r145, 0
  br i1 %r146, label %if_then_18, label %if_else_19
if_else_16:
  br label %if_merge_17
if_merge_17:
  %r147 = load i64, i64* %local1
  %r149 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r150 = ptrtoint i8* %r149 to i64
  %r151 = and i64 %r150, 281474976710655
  %r152 = or i64 %r151, 18445618173802708992
  %r148 = call i64 @tscl_object_get(i64 %r147, i64 %r152)
  %r154 = getelementptr [3 x i8], [3 x i8]* @.str.9, i64 0, i64 0
  %r155 = ptrtoint i8* %r154 to i64
  %r156 = and i64 %r155, 281474976710655
  %r153 = or i64 %r156, 18445618173802708992
  %r157 = call i64 @tscl_eq_any(i64 %r148, i64 %r153)
  %r158 = and i64 %r157, 1
  %r159 = icmp ne i64 %r158, 0
  br i1 %r159, label %if_then_33, label %if_else_34
if_then_18:
  %r161 = getelementptr [12 x i8], [12 x i8]* @.str.38, i64 0, i64 0
  %r162 = ptrtoint i8* %r161 to i64
  %r163 = and i64 %r162, 281474976710655
  %r160 = or i64 %r163, 18445618173802708992
  %r164 = call i64 @tscl_console_log(i64 %r160)
  ret i64 9221120237041090561
if_else_19:
  br label %if_merge_20
if_merge_20:
  %r165 = load i64, i64* %local1
  %r167 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r168 = ptrtoint i8* %r167 to i64
  %r169 = and i64 %r168, 281474976710655
  %r170 = or i64 %r169, 18445618173802708992
  %r166 = call i64 @tscl_object_get(i64 %r165, i64 %r170)
  %r172 = getelementptr [10 x i8], [10 x i8]* @.str.57, i64 0, i64 0
  %r173 = ptrtoint i8* %r172 to i64
  %r174 = and i64 %r173, 281474976710655
  %r171 = or i64 %r174, 18445618173802708992
  %r175 = load i64, i64* %local4
  %r177 = getelementptr [5 x i8], [5 x i8]* @.str.39, i64 0, i64 0
  %r178 = ptrtoint i8* %r177 to i64
  %r179 = and i64 %r178, 281474976710655
  %r180 = or i64 %r179, 18445618173802708992
  %r176 = call i64 @tscl_object_get(i64 %r175, i64 %r180)
  %r181 = call i64 @tscl_array_length(i64 %r176)
  %r182 = call i64 @tscl_add_any(i64 %r171, i64 %r181)
  %r184 = getelementptr [12 x i8], [12 x i8]* @.str.40, i64 0, i64 0
  %r185 = ptrtoint i8* %r184 to i64
  %r186 = and i64 %r185, 281474976710655
  %r183 = or i64 %r186, 18445618173802708992
  %r187 = call i64 @tscl_add_any(i64 %r182, i64 %r183)
  %r188 = call i64 @logVerbose(i64 %r166, i64 %r187)
  %r189 = load i64, i64* %local4
  %r191 = getelementptr [7 x i8], [7 x i8]* @.str.58, i64 0, i64 0
  %r192 = ptrtoint i8* %r191 to i64
  %r193 = and i64 %r192, 281474976710655
  %r190 = or i64 %r193, 18445618173802708992
  %r195 = getelementptr [9 x i8], [9 x i8]* @.str.59, i64 0, i64 0
  %r196 = ptrtoint i8* %r195 to i64
  %r197 = and i64 %r196, 281474976710655
  %r198 = or i64 %r197, 18445618173802708992
  %r194 = call i64 @tscl_object_get(i64 %r190, i64 %r198)
  %r199 = call i64 %r194(i64 %r189)
  store i64 %r199, i64* %local5
  %r200 = load i64, i64* %local5
  %r202 = getelementptr [7 x i8], [7 x i8]* @.str.60, i64 0, i64 0
  %r203 = ptrtoint i8* %r202 to i64
  %r204 = and i64 %r203, 281474976710655
  %r205 = or i64 %r204, 18445618173802708992
  %r201 = call i64 @tscl_object_get(i64 %r200, i64 %r205)
  %r206 = call i64 @tscl_array_length(i64 %r201)
  %r208 = call i64 @tscl_box_number(double 0.0)
  %r209 = call i64 @tscl_gt_any(i64 %r206, i64 %r208)
  %r210 = and i64 %r209, 1
  %r211 = icmp ne i64 %r210, 0
  br i1 %r211, label %if_then_21, label %if_else_22
if_then_21:
  %r213 = getelementptr [21 x i8], [21 x i8]* @.str.61, i64 0, i64 0
  %r214 = ptrtoint i8* %r213 to i64
  %r215 = and i64 %r214, 281474976710655
  %r212 = or i64 %r215, 18445618173802708992
  %r216 = call i64 @tscl_console_log(i64 %r212)
  %r218 = call i64 @tscl_box_number(double 0.0)
  store i64 %r218, i64* %local6
  br label %while_cond_24
if_else_22:
  br label %if_merge_23
if_merge_23:
  %r219 = load i64, i64* %local4
  %r220 = call i64 @lowerProgramToIr(i64 %r219)
  store i64 %r220, i64* %local7
  %r221 = load i64, i64* %local7
  %r222 = add i64 0, 9221120237041090561
  %r223 = call i64 @tscl_eq_any(i64 %r221, i64 %r222)
  %r224 = and i64 %r223, 1
  %r225 = icmp ne i64 %r224, 0
  br i1 %r225, label %if_then_27, label %if_else_28
while_cond_24:
  %r226 = load i64, i64* %local6
  %r227 = load i64, i64* %local5
  %r229 = getelementptr [7 x i8], [7 x i8]* @.str.60, i64 0, i64 0
  %r230 = ptrtoint i8* %r229 to i64
  %r231 = and i64 %r230, 281474976710655
  %r232 = or i64 %r231, 18445618173802708992
  %r228 = call i64 @tscl_object_get(i64 %r227, i64 %r232)
  %r233 = call i64 @tscl_array_length(i64 %r228)
  %r234 = call i64 @tscl_lt_any(i64 %r226, i64 %r233)
  %r235 = and i64 %r234, 1
  %r236 = icmp ne i64 %r235, 0
  br i1 %r236, label %while_body_25, label %while_exit_26
while_body_25:
  %r238 = getelementptr [3 x i8], [3 x i8]* @.str.35, i64 0, i64 0
  %r239 = ptrtoint i8* %r238 to i64
  %r240 = and i64 %r239, 281474976710655
  %r237 = or i64 %r240, 18445618173802708992
  %r241 = load i64, i64* %local5
  %r243 = getelementptr [7 x i8], [7 x i8]* @.str.60, i64 0, i64 0
  %r244 = ptrtoint i8* %r243 to i64
  %r245 = and i64 %r244, 281474976710655
  %r246 = or i64 %r245, 18445618173802708992
  %r242 = call i64 @tscl_object_get(i64 %r241, i64 %r246)
  %r247 = load i64, i64* %local6
  %r248 = call i64 @tscl_array_get(i64 %r242, i64 %r247)
  %r250 = getelementptr [12 x i8], [12 x i8]* @.str.62, i64 0, i64 0
  %r251 = ptrtoint i8* %r250 to i64
  %r252 = and i64 %r251, 281474976710655
  %r249 = or i64 %r252, 18445618173802708992
  %r254 = getelementptr [12 x i8], [12 x i8]* @.str.63, i64 0, i64 0
  %r255 = ptrtoint i8* %r254 to i64
  %r256 = and i64 %r255, 281474976710655
  %r257 = or i64 %r256, 18445618173802708992
  %r253 = call i64 @tscl_object_get(i64 %r249, i64 %r257)
  %r258 = call i64 %r253(i64 %r248)
  %r259 = call i64 @tscl_add_any(i64 %r237, i64 %r258)
  %r260 = call i64 @tscl_console_log(i64 %r259)
  %r261 = load i64, i64* %local6
  %r263 = call i64 @tscl_box_number(double 1.0)
  %r264 = call i64 @tscl_add_any(i64 %r261, i64 %r263)
  store i64 %r264, i64* %local6
  br label %while_cond_24
while_exit_26:
  ret i64 9221120237041090561
if_then_27:
  %r266 = getelementptr [18 x i8], [18 x i8]* @.str.42, i64 0, i64 0
  %r267 = ptrtoint i8* %r266 to i64
  %r268 = and i64 %r267, 281474976710655
  %r265 = or i64 %r268, 18445618173802708992
  %r269 = call i64 @tscl_console_log(i64 %r265)
  ret i64 9221120237041090561
if_else_28:
  br label %if_merge_29
if_merge_29:
  %r270 = load i64, i64* %local7
  %r272 = getelementptr [7 x i8], [7 x i8]* @.str.58, i64 0, i64 0
  %r273 = ptrtoint i8* %r272 to i64
  %r274 = and i64 %r273, 281474976710655
  %r271 = or i64 %r274, 18445618173802708992
  %r276 = getelementptr [10 x i8], [10 x i8]* @.str.64, i64 0, i64 0
  %r277 = ptrtoint i8* %r276 to i64
  %r278 = and i64 %r277, 281474976710655
  %r279 = or i64 %r278, 18445618173802708992
  %r275 = call i64 @tscl_object_get(i64 %r271, i64 %r279)
  %r280 = call i64 %r275(i64 %r270)
  %r281 = load i64, i64* %local1
  %r283 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r284 = ptrtoint i8* %r283 to i64
  %r285 = and i64 %r284, 281474976710655
  %r286 = or i64 %r285, 18445618173802708992
  %r282 = call i64 @tscl_object_get(i64 %r281, i64 %r286)
  %r288 = getelementptr [20 x i8], [20 x i8]* @.str.65, i64 0, i64 0
  %r289 = ptrtoint i8* %r288 to i64
  %r290 = and i64 %r289, 281474976710655
  %r287 = or i64 %r290, 18445618173802708992
  %r291 = call i64 @logVerbose(i64 %r282, i64 %r287)
  %r292 = load i64, i64* %local7
  %r294 = getelementptr [7 x i8], [7 x i8]* @.str.58, i64 0, i64 0
  %r295 = ptrtoint i8* %r294 to i64
  %r296 = and i64 %r295, 281474976710655
  %r293 = or i64 %r296, 18445618173802708992
  %r298 = getelementptr [9 x i8], [9 x i8]* @.str.66, i64 0, i64 0
  %r299 = ptrtoint i8* %r298 to i64
  %r300 = and i64 %r299, 281474976710655
  %r301 = or i64 %r300, 18445618173802708992
  %r297 = call i64 @tscl_object_get(i64 %r293, i64 %r301)
  %r302 = call i64 %r297(i64 %r292)
  %r303 = load i64, i64* %local1
  %r305 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r306 = ptrtoint i8* %r305 to i64
  %r307 = and i64 %r306, 281474976710655
  %r308 = or i64 %r307, 18445618173802708992
  %r304 = call i64 @tscl_object_get(i64 %r303, i64 %r308)
  %r310 = getelementptr [22 x i8], [22 x i8]* @.str.67, i64 0, i64 0
  %r311 = ptrtoint i8* %r310 to i64
  %r312 = and i64 %r311, 281474976710655
  %r309 = or i64 %r312, 18445618173802708992
  %r313 = call i64 @logVerbose(i64 %r304, i64 %r309)
  %r315 = getelementptr [18 x i8], [18 x i8]* @.str.68, i64 0, i64 0
  %r316 = ptrtoint i8* %r315 to i64
  %r317 = and i64 %r316, 281474976710655
  %r314 = or i64 %r317, 18445618173802708992
  %r318 = call i64 @tscl_console_log(i64 %r314)
  %r319 = load i64, i64* %local7
  %r320 = call i64 @verifyIrModule(i64 %r319)
  %r322 = and i64 %r320, 1
  %r323 = icmp eq i64 %r322, 0
  %r321 = select i1 %r323, i64 9221120237041090561, i64 9221120237041090560
  %r324 = and i64 %r321, 1
  %r325 = icmp ne i64 %r324, 0
  br i1 %r325, label %if_then_30, label %if_else_31
if_then_30:
  %r327 = getelementptr [23 x i8], [23 x i8]* @.str.46, i64 0, i64 0
  %r328 = ptrtoint i8* %r327 to i64
  %r329 = and i64 %r328, 281474976710655
  %r326 = or i64 %r329, 18445618173802708992
  %r330 = call i64 @tscl_console_log(i64 %r326)
  ret i64 9221120237041090561
if_else_31:
  br label %if_merge_32
if_merge_32:
  %r332 = getelementptr [14 x i8], [14 x i8]* @.str.69, i64 0, i64 0
  %r333 = ptrtoint i8* %r332 to i64
  %r334 = and i64 %r333, 281474976710655
  %r331 = or i64 %r334, 18445618173802708992
  %r335 = call i64 @tscl_console_log(i64 %r331)
  %r337 = getelementptr [15 x i8], [15 x i8]* @.str.70, i64 0, i64 0
  %r338 = ptrtoint i8* %r337 to i64
  %r339 = and i64 %r338, 281474976710655
  %r336 = or i64 %r339, 18445618173802708992
  %r340 = load i64, i64* %local1
  %r342 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r343 = ptrtoint i8* %r342 to i64
  %r344 = and i64 %r343, 281474976710655
  %r345 = or i64 %r344, 18445618173802708992
  %r341 = call i64 @tscl_object_get(i64 %r340, i64 %r345)
  %r346 = call i64 @tscl_add_any(i64 %r336, i64 %r341)
  %r347 = call i64 @tscl_console_log(i64 %r346)
  ret i64 9221120237041090561
if_then_33:
  %r348 = load i64, i64* %local2
  %r349 = load i64, i64* %local1
  %r351 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r352 = ptrtoint i8* %r351 to i64
  %r353 = and i64 %r352, 281474976710655
  %r354 = or i64 %r353, 18445618173802708992
  %r350 = call i64 @tscl_object_get(i64 %r349, i64 %r354)
  %r355 = call i64 @compileSource(i64 %r348, i64 %r350)
  store i64 %r355, i64* %local8
  %r356 = load i64, i64* %local8
  %r357 = add i64 0, 9221120237041090561
  %r358 = call i64 @tscl_ne_any(i64 %r356, i64 %r357)
  %r359 = and i64 %r358, 1
  %r360 = icmp ne i64 %r359, 0
  br i1 %r360, label %if_then_36, label %if_else_37
if_else_34:
  br label %if_merge_35
if_merge_35:
  %r361 = load i64, i64* %local1
  %r363 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r364 = ptrtoint i8* %r363 to i64
  %r365 = and i64 %r364, 281474976710655
  %r366 = or i64 %r365, 18445618173802708992
  %r362 = call i64 @tscl_object_get(i64 %r361, i64 %r366)
  %r368 = getelementptr [5 x i8], [5 x i8]* @.str.12, i64 0, i64 0
  %r369 = ptrtoint i8* %r368 to i64
  %r370 = and i64 %r369, 281474976710655
  %r367 = or i64 %r370, 18445618173802708992
  %r371 = call i64 @tscl_eq_any(i64 %r362, i64 %r367)
  %r372 = and i64 %r371, 1
  %r373 = icmp ne i64 %r372, 0
  br i1 %r373, label %if_then_42, label %if_else_43
if_then_36:
  %r374 = load i64, i64* %local8
  %r375 = call i64 @serializeIrModule(i64 %r374)
  store i64 %r375, i64* %local9
  %r376 = load i64, i64* %local1
  %r378 = getelementptr [11 x i8], [11 x i8]* @.str.4, i64 0, i64 0
  %r379 = ptrtoint i8* %r378 to i64
  %r380 = and i64 %r379, 281474976710655
  %r381 = or i64 %r380, 18445618173802708992
  %r377 = call i64 @tscl_object_get(i64 %r376, i64 %r381)
  %r383 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r384 = ptrtoint i8* %r383 to i64
  %r385 = and i64 %r384, 281474976710655
  %r382 = or i64 %r385, 18445618173802708992
  %r386 = call i64 @tscl_ne_any(i64 %r377, i64 %r382)
  %r387 = and i64 %r386, 1
  %r388 = icmp ne i64 %r387, 0
  br i1 %r388, label %if_then_39, label %if_else_40
if_else_37:
  br label %if_merge_38
if_merge_38:
  ret i64 9221120237041090561
if_then_39:
  %r389 = load i64, i64* %local1
  %r391 = getelementptr [11 x i8], [11 x i8]* @.str.4, i64 0, i64 0
  %r392 = ptrtoint i8* %r391 to i64
  %r393 = and i64 %r392, 281474976710655
  %r394 = or i64 %r393, 18445618173802708992
  %r390 = call i64 @tscl_object_get(i64 %r389, i64 %r394)
  %r395 = load i64, i64* %local9
  %r397 = getelementptr [3 x i8], [3 x i8]* @.str.49, i64 0, i64 0
  %r398 = ptrtoint i8* %r397 to i64
  %r399 = and i64 %r398, 281474976710655
  %r396 = or i64 %r399, 18445618173802708992
  %r401 = getelementptr [14 x i8], [14 x i8]* @.str.71, i64 0, i64 0
  %r402 = ptrtoint i8* %r401 to i64
  %r403 = and i64 %r402, 281474976710655
  %r404 = or i64 %r403, 18445618173802708992
  %r400 = call i64 @tscl_object_get(i64 %r396, i64 %r404)
  %r405 = call i64 %r400(i64 %r390, i64 %r395)
  br label %if_merge_41
if_else_40:
  %r406 = load i64, i64* %local9
  %r407 = call i64 @tscl_console_log(i64 %r406)
  br label %if_merge_41
if_merge_41:
  br label %if_merge_38
if_then_42:
  %r408 = load i64, i64* %local1
  %r410 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r411 = ptrtoint i8* %r410 to i64
  %r412 = and i64 %r411, 281474976710655
  %r413 = or i64 %r412, 18445618173802708992
  %r409 = call i64 @tscl_object_get(i64 %r408, i64 %r413)
  %r415 = getelementptr [24 x i8], [24 x i8]* @.str.72, i64 0, i64 0
  %r416 = ptrtoint i8* %r415 to i64
  %r417 = and i64 %r416, 281474976710655
  %r414 = or i64 %r417, 18445618173802708992
  %r418 = call i64 @logVerbose(i64 %r409, i64 %r414)
  %r419 = load i64, i64* %local2
  %r420 = load i64, i64* %local1
  %r422 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r423 = ptrtoint i8* %r422 to i64
  %r424 = and i64 %r423, 281474976710655
  %r425 = or i64 %r424, 18445618173802708992
  %r421 = call i64 @tscl_object_get(i64 %r420, i64 %r425)
  %r426 = call i64 @compileSource(i64 %r419, i64 %r421)
  store i64 %r426, i64* %local10
  %r427 = load i64, i64* %local10
  %r428 = add i64 0, 9221120237041090561
  %r429 = call i64 @tscl_eq_any(i64 %r427, i64 %r428)
  %r430 = and i64 %r429, 1
  %r431 = icmp ne i64 %r430, 0
  br i1 %r431, label %if_then_45, label %if_else_46
if_else_43:
  br label %if_merge_44
if_merge_44:
  %r432 = load i64, i64* %local1
  %r434 = getelementptr [8 x i8], [8 x i8]* @.str.1, i64 0, i64 0
  %r435 = ptrtoint i8* %r434 to i64
  %r436 = and i64 %r435, 281474976710655
  %r437 = or i64 %r436, 18445618173802708992
  %r433 = call i64 @tscl_object_get(i64 %r432, i64 %r437)
  %r439 = getelementptr [6 x i8], [6 x i8]* @.str.8, i64 0, i64 0
  %r440 = ptrtoint i8* %r439 to i64
  %r441 = and i64 %r440, 281474976710655
  %r438 = or i64 %r441, 18445618173802708992
  %r442 = call i64 @tscl_eq_any(i64 %r433, i64 %r438)
  %r443 = and i64 %r442, 1
  %r444 = icmp ne i64 %r443, 0
  br i1 %r444, label %if_then_54, label %if_else_55
if_then_45:
  %r446 = getelementptr [19 x i8], [19 x i8]* @.str.73, i64 0, i64 0
  %r447 = ptrtoint i8* %r446 to i64
  %r448 = and i64 %r447, 281474976710655
  %r445 = or i64 %r448, 18445618173802708992
  %r449 = call i64 @tscl_console_log(i64 %r445)
  ret i64 9221120237041090561
if_else_46:
  br label %if_merge_47
if_merge_47:
  %r450 = load i64, i64* %local1
  %r452 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r453 = ptrtoint i8* %r452 to i64
  %r454 = and i64 %r453, 281474976710655
  %r455 = or i64 %r454, 18445618173802708992
  %r451 = call i64 @tscl_object_get(i64 %r450, i64 %r455)
  %r457 = getelementptr [22 x i8], [22 x i8]* @.str.74, i64 0, i64 0
  %r458 = ptrtoint i8* %r457 to i64
  %r459 = and i64 %r458, 281474976710655
  %r456 = or i64 %r459, 18445618173802708992
  %r460 = call i64 @logVerbose(i64 %r451, i64 %r456)
  %r461 = load i64, i64* %local10
  %r462 = call i64 @emitLlvmModule(i64 %r461)
  store i64 %r462, i64* %local11
  %r463 = load i64, i64* %local1
  %r465 = getelementptr [11 x i8], [11 x i8]* @.str.4, i64 0, i64 0
  %r466 = ptrtoint i8* %r465 to i64
  %r467 = and i64 %r466, 281474976710655
  %r468 = or i64 %r467, 18445618173802708992
  %r464 = call i64 @tscl_object_get(i64 %r463, i64 %r468)
  store i64 %r464, i64* %local12
  %r469 = load i64, i64* %local12
  %r471 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r472 = ptrtoint i8* %r471 to i64
  %r473 = and i64 %r472, 281474976710655
  %r470 = or i64 %r473, 18445618173802708992
  %r474 = call i64 @tscl_eq_any(i64 %r469, i64 %r470)
  %r475 = and i64 %r474, 1
  %r476 = icmp ne i64 %r475, 0
  br i1 %r476, label %if_then_48, label %if_else_49
if_then_48:
  %r478 = getelementptr [6 x i8], [6 x i8]* @.str.75, i64 0, i64 0
  %r479 = ptrtoint i8* %r478 to i64
  %r480 = and i64 %r479, 281474976710655
  %r477 = or i64 %r480, 18445618173802708992
  %r481 = load i64, i64* %local1
  %r483 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r484 = ptrtoint i8* %r483 to i64
  %r485 = and i64 %r484, 281474976710655
  %r486 = or i64 %r485, 18445618173802708992
  %r482 = call i64 @tscl_object_get(i64 %r481, i64 %r486)
  %r488 = getelementptr [8 x i8], [8 x i8]* @.str.76, i64 0, i64 0
  %r489 = ptrtoint i8* %r488 to i64
  %r490 = and i64 %r489, 281474976710655
  %r491 = or i64 %r490, 18445618173802708992
  %r487 = call i64 @tscl_object_get(i64 %r482, i64 %r491)
  %r492 = call i64 %r487(i64 %r477)
  %r494 = call i64 @tscl_box_number(double 0.0)
  %r495 = call i64 @tscl_gt_any(i64 %r492, i64 %r494)
  %r496 = and i64 %r495, 1
  %r497 = icmp ne i64 %r496, 0
  br i1 %r497, label %if_then_51, label %if_else_52
if_else_49:
  br label %if_merge_50
if_merge_50:
  %r498 = load i64, i64* %local12
  %r499 = load i64, i64* %local11
  %r501 = getelementptr [3 x i8], [3 x i8]* @.str.49, i64 0, i64 0
  %r502 = ptrtoint i8* %r501 to i64
  %r503 = and i64 %r502, 281474976710655
  %r500 = or i64 %r503, 18445618173802708992
  %r505 = getelementptr [14 x i8], [14 x i8]* @.str.71, i64 0, i64 0
  %r506 = ptrtoint i8* %r505 to i64
  %r507 = and i64 %r506, 281474976710655
  %r508 = or i64 %r507, 18445618173802708992
  %r504 = call i64 @tscl_object_get(i64 %r500, i64 %r508)
  %r509 = call i64 %r504(i64 %r498, i64 %r499)
  %r511 = getelementptr [12 x i8], [12 x i8]* @.str.77, i64 0, i64 0
  %r512 = ptrtoint i8* %r511 to i64
  %r513 = and i64 %r512, 281474976710655
  %r510 = or i64 %r513, 18445618173802708992
  %r514 = load i64, i64* %local12
  %r515 = call i64 @tscl_add_any(i64 %r510, i64 %r514)
  %r516 = call i64 @tscl_console_log(i64 %r515)
  %r518 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r519 = ptrtoint i8* %r518 to i64
  %r520 = and i64 %r519, 281474976710655
  %r517 = or i64 %r520, 18445618173802708992
  %r521 = call i64 @tscl_console_log(i64 %r517)
  %r523 = getelementptr [29 x i8], [29 x i8]* @.str.78, i64 0, i64 0
  %r524 = ptrtoint i8* %r523 to i64
  %r525 = and i64 %r524, 281474976710655
  %r522 = or i64 %r525, 18445618173802708992
  %r526 = call i64 @tscl_console_log(i64 %r522)
  %r528 = getelementptr [21 x i8], [21 x i8]* @.str.79, i64 0, i64 0
  %r529 = ptrtoint i8* %r528 to i64
  %r530 = and i64 %r529, 281474976710655
  %r527 = or i64 %r530, 18445618173802708992
  %r531 = load i64, i64* %local12
  %r532 = call i64 @tscl_add_any(i64 %r527, i64 %r531)
  %r534 = getelementptr [13 x i8], [13 x i8]* @.str.80, i64 0, i64 0
  %r535 = ptrtoint i8* %r534 to i64
  %r536 = and i64 %r535, 281474976710655
  %r533 = or i64 %r536, 18445618173802708992
  %r537 = call i64 @tscl_add_any(i64 %r532, i64 %r533)
  %r538 = call i64 @tscl_console_log(i64 %r537)
  %r540 = getelementptr [27 x i8], [27 x i8]* @.str.81, i64 0, i64 0
  %r541 = ptrtoint i8* %r540 to i64
  %r542 = and i64 %r541, 281474976710655
  %r539 = or i64 %r542, 18445618173802708992
  %r543 = call i64 @tscl_console_log(i64 %r539)
  ret i64 9221120237041090561
if_then_51:
  %r545 = call i64 @tscl_box_number(double 0.0)
  %r547 = getelementptr [6 x i8], [6 x i8]* @.str.75, i64 0, i64 0
  %r548 = ptrtoint i8* %r547 to i64
  %r549 = and i64 %r548, 281474976710655
  %r546 = or i64 %r549, 18445618173802708992
  %r550 = load i64, i64* %local1
  %r552 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r553 = ptrtoint i8* %r552 to i64
  %r554 = and i64 %r553, 281474976710655
  %r555 = or i64 %r554, 18445618173802708992
  %r551 = call i64 @tscl_object_get(i64 %r550, i64 %r555)
  %r557 = getelementptr [8 x i8], [8 x i8]* @.str.76, i64 0, i64 0
  %r558 = ptrtoint i8* %r557 to i64
  %r559 = and i64 %r558, 281474976710655
  %r560 = or i64 %r559, 18445618173802708992
  %r556 = call i64 @tscl_object_get(i64 %r551, i64 %r560)
  %r561 = call i64 %r556(i64 %r546)
  %r562 = load i64, i64* %local1
  %r564 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r565 = ptrtoint i8* %r564 to i64
  %r566 = and i64 %r565, 281474976710655
  %r567 = or i64 %r566, 18445618173802708992
  %r563 = call i64 @tscl_object_get(i64 %r562, i64 %r567)
  %r569 = getelementptr [10 x i8], [10 x i8]* @.str.82, i64 0, i64 0
  %r570 = ptrtoint i8* %r569 to i64
  %r571 = and i64 %r570, 281474976710655
  %r572 = or i64 %r571, 18445618173802708992
  %r568 = call i64 @tscl_object_get(i64 %r563, i64 %r572)
  %r573 = call i64 %r568(i64 %r545, i64 %r561)
  %r575 = getelementptr [4 x i8], [4 x i8]* @.str.83, i64 0, i64 0
  %r576 = ptrtoint i8* %r575 to i64
  %r577 = and i64 %r576, 281474976710655
  %r574 = or i64 %r577, 18445618173802708992
  %r578 = call i64 @tscl_add_any(i64 %r573, i64 %r574)
  store i64 %r578, i64* %local12
  br label %if_merge_53
if_else_52:
  %r579 = load i64, i64* %local1
  %r581 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r582 = ptrtoint i8* %r581 to i64
  %r583 = and i64 %r582, 281474976710655
  %r584 = or i64 %r583, 18445618173802708992
  %r580 = call i64 @tscl_object_get(i64 %r579, i64 %r584)
  %r586 = getelementptr [4 x i8], [4 x i8]* @.str.83, i64 0, i64 0
  %r587 = ptrtoint i8* %r586 to i64
  %r588 = and i64 %r587, 281474976710655
  %r585 = or i64 %r588, 18445618173802708992
  %r589 = call i64 @tscl_add_any(i64 %r580, i64 %r585)
  store i64 %r589, i64* %local12
  br label %if_merge_53
if_merge_53:
  br label %if_merge_50
if_then_54:
  %r590 = load i64, i64* %local1
  %r592 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r593 = ptrtoint i8* %r592 to i64
  %r594 = and i64 %r593, 281474976710655
  %r595 = or i64 %r594, 18445618173802708992
  %r591 = call i64 @tscl_object_get(i64 %r590, i64 %r595)
  %r597 = getelementptr [25 x i8], [25 x i8]* @.str.84, i64 0, i64 0
  %r598 = ptrtoint i8* %r597 to i64
  %r599 = and i64 %r598, 281474976710655
  %r596 = or i64 %r599, 18445618173802708992
  %r600 = call i64 @logVerbose(i64 %r591, i64 %r596)
  %r601 = load i64, i64* %local2
  %r602 = call i64 @parseSource(i64 %r601)
  store i64 %r602, i64* %local13
  %r603 = load i64, i64* %local13
  %r604 = add i64 0, 9221120237041090561
  %r605 = call i64 @tscl_eq_any(i64 %r603, i64 %r604)
  %r606 = and i64 %r605, 1
  %r607 = icmp ne i64 %r606, 0
  br i1 %r607, label %if_then_57, label %if_else_58
if_else_55:
  br label %if_merge_56
if_merge_56:
  %r608 = load i64, i64* %local1
  %r610 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r611 = ptrtoint i8* %r610 to i64
  %r612 = and i64 %r611, 281474976710655
  %r613 = or i64 %r612, 18445618173802708992
  %r609 = call i64 @tscl_object_get(i64 %r608, i64 %r613)
  %r615 = getelementptr [27 x i8], [27 x i8]* @.str.85, i64 0, i64 0
  %r616 = ptrtoint i8* %r615 to i64
  %r617 = and i64 %r616, 281474976710655
  %r614 = or i64 %r617, 18445618173802708992
  %r618 = call i64 @logVerbose(i64 %r609, i64 %r614)
  %r619 = load i64, i64* %local2
  %r620 = call i64 @parseSource(i64 %r619)
  store i64 %r620, i64* %local16
  %r621 = load i64, i64* %local16
  %r622 = add i64 0, 9221120237041090561
  %r623 = call i64 @tscl_eq_any(i64 %r621, i64 %r622)
  %r624 = and i64 %r623, 1
  %r625 = icmp ne i64 %r624, 0
  br i1 %r625, label %if_then_66, label %if_else_67
if_then_57:
  %r627 = getelementptr [12 x i8], [12 x i8]* @.str.38, i64 0, i64 0
  %r628 = ptrtoint i8* %r627 to i64
  %r629 = and i64 %r628, 281474976710655
  %r626 = or i64 %r629, 18445618173802708992
  %r630 = call i64 @tscl_console_log(i64 %r626)
  ret i64 9221120237041090561
if_else_58:
  br label %if_merge_59
if_merge_59:
  %r631 = load i64, i64* %local1
  %r633 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r634 = ptrtoint i8* %r633 to i64
  %r635 = and i64 %r634, 281474976710655
  %r636 = or i64 %r635, 18445618173802708992
  %r632 = call i64 @tscl_object_get(i64 %r631, i64 %r636)
  %r638 = getelementptr [10 x i8], [10 x i8]* @.str.57, i64 0, i64 0
  %r639 = ptrtoint i8* %r638 to i64
  %r640 = and i64 %r639, 281474976710655
  %r637 = or i64 %r640, 18445618173802708992
  %r641 = load i64, i64* %local13
  %r643 = getelementptr [5 x i8], [5 x i8]* @.str.39, i64 0, i64 0
  %r644 = ptrtoint i8* %r643 to i64
  %r645 = and i64 %r644, 281474976710655
  %r646 = or i64 %r645, 18445618173802708992
  %r642 = call i64 @tscl_object_get(i64 %r641, i64 %r646)
  %r647 = call i64 @tscl_array_length(i64 %r642)
  %r648 = call i64 @tscl_add_any(i64 %r637, i64 %r647)
  %r650 = getelementptr [12 x i8], [12 x i8]* @.str.40, i64 0, i64 0
  %r651 = ptrtoint i8* %r650 to i64
  %r652 = and i64 %r651, 281474976710655
  %r649 = or i64 %r652, 18445618173802708992
  %r653 = call i64 @tscl_add_any(i64 %r648, i64 %r649)
  %r654 = call i64 @logVerbose(i64 %r632, i64 %r653)
  %r655 = load i64, i64* %local13
  %r657 = getelementptr [8 x i8], [8 x i8]* @.str.86, i64 0, i64 0
  %r658 = ptrtoint i8* %r657 to i64
  %r659 = and i64 %r658, 281474976710655
  %r656 = or i64 %r659, 18445618173802708992
  %r661 = getelementptr [11 x i8], [11 x i8]* @.str.87, i64 0, i64 0
  %r662 = ptrtoint i8* %r661 to i64
  %r663 = and i64 %r662, 281474976710655
  %r664 = or i64 %r663, 18445618173802708992
  %r660 = call i64 @tscl_object_get(i64 %r656, i64 %r664)
  %r665 = call i64 %r660(i64 %r655)
  store i64 %r665, i64* %local14
  %r666 = load i64, i64* %local14
  %r667 = add i64 0, 9221120237041090561
  %r668 = call i64 @tscl_eq_any(i64 %r666, i64 %r667)
  %r669 = and i64 %r668, 1
  %r670 = icmp ne i64 %r669, 0
  br i1 %r670, label %if_then_60, label %if_else_61
if_then_60:
  %r672 = getelementptr [27 x i8], [27 x i8]* @.str.88, i64 0, i64 0
  %r673 = ptrtoint i8* %r672 to i64
  %r674 = and i64 %r673, 281474976710655
  %r671 = or i64 %r674, 18445618173802708992
  %r675 = call i64 @tscl_console_log(i64 %r671)
  ret i64 9221120237041090561
if_else_61:
  br label %if_merge_62
if_merge_62:
  %r676 = load i64, i64* %local1
  %r678 = getelementptr [8 x i8], [8 x i8]* @.str.7, i64 0, i64 0
  %r679 = ptrtoint i8* %r678 to i64
  %r680 = and i64 %r679, 281474976710655
  %r681 = or i64 %r680, 18445618173802708992
  %r677 = call i64 @tscl_object_get(i64 %r676, i64 %r681)
  %r683 = getelementptr [13 x i8], [13 x i8]* @.str.89, i64 0, i64 0
  %r684 = ptrtoint i8* %r683 to i64
  %r685 = and i64 %r684, 281474976710655
  %r682 = or i64 %r685, 18445618173802708992
  %r686 = load i64, i64* %local14
  %r687 = call i64 @tscl_array_length(i64 %r686)
  %r688 = call i64 @tscl_add_any(i64 %r682, i64 %r687)
  %r690 = getelementptr [7 x i8], [7 x i8]* @.str.90, i64 0, i64 0
  %r691 = ptrtoint i8* %r690 to i64
  %r692 = and i64 %r691, 281474976710655
  %r689 = or i64 %r692, 18445618173802708992
  %r693 = call i64 @tscl_add_any(i64 %r688, i64 %r689)
  %r694 = call i64 @logVerbose(i64 %r677, i64 %r693)
  %r695 = load i64, i64* %local1
  %r697 = getelementptr [11 x i8], [11 x i8]* @.str.4, i64 0, i64 0
  %r698 = ptrtoint i8* %r697 to i64
  %r699 = and i64 %r698, 281474976710655
  %r700 = or i64 %r699, 18445618173802708992
  %r696 = call i64 @tscl_object_get(i64 %r695, i64 %r700)
  store i64 %r696, i64* %local15
  %r701 = load i64, i64* %local15
  %r703 = getelementptr [1 x i8], [1 x i8]* @.str.2, i64 0, i64 0
  %r704 = ptrtoint i8* %r703 to i64
  %r705 = and i64 %r704, 281474976710655
  %r702 = or i64 %r705, 18445618173802708992
  %r706 = call i64 @tscl_eq_any(i64 %r701, i64 %r702)
  %r707 = and i64 %r706, 1
  %r708 = icmp ne i64 %r707, 0
  br i1 %r708, label %if_then_63, label %if_else_64
if_then_63:
  %r709 = load i64, i64* %local1
  %r711 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r712 = ptrtoint i8* %r711 to i64
  %r713 = and i64 %r712, 281474976710655
  %r714 = or i64 %r713, 18445618173802708992
  %r710 = call i64 @tscl_object_get(i64 %r709, i64 %r714)
  %r716 = getelementptr [4 x i8], [4 x i8]* @.str.91, i64 0, i64 0
  %r717 = ptrtoint i8* %r716 to i64
  %r718 = and i64 %r717, 281474976710655
  %r715 = or i64 %r718, 18445618173802708992
  %r719 = call i64 @tscl_add_any(i64 %r710, i64 %r715)
  store i64 %r719, i64* %local15
  br label %if_merge_65
if_else_64:
  br label %if_merge_65
if_merge_65:
  %r720 = load i64, i64* %local15
  %r721 = load i64, i64* %local14
  %r723 = getelementptr [9 x i8], [9 x i8]* @.str.92, i64 0, i64 0
  %r724 = ptrtoint i8* %r723 to i64
  %r725 = and i64 %r724, 281474976710655
  %r726 = or i64 %r725, 18445618173802708992
  %r722 = call i64 @tscl_object_get(i64 %r721, i64 %r726)
  %r728 = getelementptr [3 x i8], [3 x i8]* @.str.49, i64 0, i64 0
  %r729 = ptrtoint i8* %r728 to i64
  %r730 = and i64 %r729, 281474976710655
  %r727 = or i64 %r730, 18445618173802708992
  %r732 = getelementptr [16 x i8], [16 x i8]* @.str.93, i64 0, i64 0
  %r733 = ptrtoint i8* %r732 to i64
  %r734 = and i64 %r733, 281474976710655
  %r735 = or i64 %r734, 18445618173802708992
  %r731 = call i64 @tscl_object_get(i64 %r727, i64 %r735)
  %r736 = call i64 %r731(i64 %r720, i64 %r722)
  %r738 = getelementptr [11 x i8], [11 x i8]* @.str.94, i64 0, i64 0
  %r739 = ptrtoint i8* %r738 to i64
  %r740 = and i64 %r739, 281474976710655
  %r737 = or i64 %r740, 18445618173802708992
  %r741 = load i64, i64* %local1
  %r743 = getelementptr [10 x i8], [10 x i8]* @.str.3, i64 0, i64 0
  %r744 = ptrtoint i8* %r743 to i64
  %r745 = and i64 %r744, 281474976710655
  %r746 = or i64 %r745, 18445618173802708992
  %r742 = call i64 @tscl_object_get(i64 %r741, i64 %r746)
  %r747 = call i64 @tscl_add_any(i64 %r737, i64 %r742)
  %r749 = getelementptr [5 x i8], [5 x i8]* @.str.95, i64 0, i64 0
  %r750 = ptrtoint i8* %r749 to i64
  %r751 = and i64 %r750, 281474976710655
  %r748 = or i64 %r751, 18445618173802708992
  %r752 = call i64 @tscl_add_any(i64 %r747, i64 %r748)
  %r753 = load i64, i64* %local15
  %r754 = call i64 @tscl_add_any(i64 %r752, i64 %r753)
  %r756 = getelementptr [3 x i8], [3 x i8]* @.str.96, i64 0, i64 0
  %r757 = ptrtoint i8* %r756 to i64
  %r758 = and i64 %r757, 281474976710655
  %r755 = or i64 %r758, 18445618173802708992
  %r759 = call i64 @tscl_add_any(i64 %r754, i64 %r755)
  %r760 = load i64, i64* %local14
  %r761 = call i64 @tscl_array_length(i64 %r760)
  %r762 = call i64 @tscl_add_any(i64 %r759, i64 %r761)
  %r764 = getelementptr [8 x i8], [8 x i8]* @.str.97, i64 0, i64 0
  %r765 = ptrtoint i8* %r764 to i64
  %r766 = and i64 %r765, 281474976710655
  %r763 = or i64 %r766, 18445618173802708992
  %r767 = call i64 @tscl_add_any(i64 %r762, i64 %r763)
  %r768 = call i64 @tscl_console_log(i64 %r767)
  ret i64 9221120237041090561
if_then_66:
  %r770 = getelementptr [12 x i8], [12 x i8]* @.str.38, i64 0, i64 0
  %r771 = ptrtoint i8* %r770 to i64
  %r772 = and i64 %r771, 281474976710655
  %r769 = or i64 %r772, 18445618173802708992
  %r773 = call i64 @tscl_console_log(i64 %r769)
  ret i64 9221120237041090561
if_else_67:
  br label %if_merge_68
if_merge_68:
  %r774 = load i64, i64* %local16
  %r776 = getelementptr [8 x i8], [8 x i8]* @.str.86, i64 0, i64 0
  %r777 = ptrtoint i8* %r776 to i64
  %r778 = and i64 %r777, 281474976710655
  %r775 = or i64 %r778, 18445618173802708992
  %r780 = getelementptr [11 x i8], [11 x i8]* @.str.87, i64 0, i64 0
  %r781 = ptrtoint i8* %r780 to i64
  %r782 = and i64 %r781, 281474976710655
  %r783 = or i64 %r782, 18445618173802708992
  %r779 = call i64 @tscl_object_get(i64 %r775, i64 %r783)
  %r784 = call i64 %r779(i64 %r774)
  store i64 %r784, i64* %local17
  %r785 = load i64, i64* %local17
  %r786 = add i64 0, 9221120237041090561
  %r787 = call i64 @tscl_eq_any(i64 %r785, i64 %r786)
  %r788 = and i64 %r787, 1
  %r789 = icmp ne i64 %r788, 0
  br i1 %r789, label %if_then_69, label %if_else_70
if_then_69:
  %r791 = getelementptr [27 x i8], [27 x i8]* @.str.88, i64 0, i64 0
  %r792 = ptrtoint i8* %r791 to i64
  %r793 = and i64 %r792, 281474976710655
  %r790 = or i64 %r793, 18445618173802708992
  %r794 = call i64 @tscl_console_log(i64 %r790)
  ret i64 9221120237041090561
if_else_70:
  br label %if_merge_71
if_merge_71:
  %r796 = getelementptr [21 x i8], [21 x i8]* @.str.98, i64 0, i64 0
  %r797 = ptrtoint i8* %r796 to i64
  %r798 = and i64 %r797, 281474976710655
  %r795 = or i64 %r798, 18445618173802708992
  %r799 = load i64, i64* %local17
  %r800 = call i64 @tscl_array_length(i64 %r799)
  %r801 = call i64 @tscl_add_any(i64 %r795, i64 %r800)
  %r803 = getelementptr [8 x i8], [8 x i8]* @.str.97, i64 0, i64 0
  %r804 = ptrtoint i8* %r803 to i64
  %r805 = and i64 %r804, 281474976710655
  %r802 = or i64 %r805, 18445618173802708992
  %r806 = call i64 @tscl_add_any(i64 %r801, i64 %r802)
  %r807 = call i64 @tscl_console_log(i64 %r806)
  %r809 = getelementptr [67 x i8], [67 x i8]* @.str.99, i64 0, i64 0
  %r810 = ptrtoint i8* %r809 to i64
  %r811 = and i64 %r810, 281474976710655
  %r808 = or i64 %r811, 18445618173802708992
  %r812 = call i64 @tscl_console_log(i64 %r808)
  ret i64 9221120237041090561
}

; ============================================================
; Function: script_main
; ============================================================
define i64 @script_main() {
entry:
  %local0 = alloca i64
  br label %main_entry
main_entry:
  %r1 = add i64 0, 8
  %r0 = call i64 @tscl_alloc_object(i64 %r1)
  %r3 = getelementptr [14 x i8], [14 x i8]* @.str.100, i64 0, i64 0
  %r4 = ptrtoint i8* %r3 to i64
  %r5 = and i64 %r4, 281474976710655
  %r2 = or i64 %r5, 18445618173802708992
  %r6 = getelementptr [8 x i8], [8 x i8]* @.str.101, i64 0, i64 0
  %r7 = ptrtoint i8* %r6 to i64
  %r8 = and i64 %r7, 281474976710655
  %r9 = or i64 %r8, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r9, i64 %r2)
  %r11 = getelementptr [9 x i8], [9 x i8]* @.str.102, i64 0, i64 0
  %r12 = ptrtoint i8* %r11 to i64
  %r13 = and i64 %r12, 281474976710655
  %r10 = or i64 %r13, 18445618173802708992
  %r14 = getelementptr [18 x i8], [18 x i8]* @.str.103, i64 0, i64 0
  %r15 = ptrtoint i8* %r14 to i64
  %r16 = and i64 %r15, 281474976710655
  %r17 = or i64 %r16, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r17, i64 %r10)
  %r19 = getelementptr [9 x i8], [9 x i8]* @.str.104, i64 0, i64 0
  %r20 = ptrtoint i8* %r19 to i64
  %r21 = and i64 %r20, 281474976710655
  %r18 = or i64 %r21, 18445618173802708992
  %r22 = getelementptr [14 x i8], [14 x i8]* @.str.105, i64 0, i64 0
  %r23 = ptrtoint i8* %r22 to i64
  %r24 = and i64 %r23, 281474976710655
  %r25 = or i64 %r24, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r25, i64 %r18)
  %r27 = getelementptr [12 x i8], [12 x i8]* @.str.106, i64 0, i64 0
  %r28 = ptrtoint i8* %r27 to i64
  %r29 = and i64 %r28, 281474976710655
  %r26 = or i64 %r29, 18445618173802708992
  %r30 = getelementptr [6 x i8], [6 x i8]* @.str.107, i64 0, i64 0
  %r31 = ptrtoint i8* %r30 to i64
  %r32 = and i64 %r31, 281474976710655
  %r33 = or i64 %r32, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r33, i64 %r26)
  %r35 = getelementptr [9 x i8], [9 x i8]* @.str.108, i64 0, i64 0
  %r36 = ptrtoint i8* %r35 to i64
  %r37 = and i64 %r36, 281474976710655
  %r34 = or i64 %r37, 18445618173802708992
  %r38 = getelementptr [9 x i8], [9 x i8]* @.str.108, i64 0, i64 0
  %r39 = ptrtoint i8* %r38 to i64
  %r40 = and i64 %r39, 281474976710655
  %r41 = or i64 %r40, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r41, i64 %r34)
  %r43 = getelementptr [17 x i8], [17 x i8]* @.str.109, i64 0, i64 0
  %r44 = ptrtoint i8* %r43 to i64
  %r45 = and i64 %r44, 281474976710655
  %r42 = or i64 %r45, 18445618173802708992
  %r46 = getelementptr [10 x i8], [10 x i8]* @.str.110, i64 0, i64 0
  %r47 = ptrtoint i8* %r46 to i64
  %r48 = and i64 %r47, 281474976710655
  %r49 = or i64 %r48, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r49, i64 %r42)
  %r51 = getelementptr [15 x i8], [15 x i8]* @.str.111, i64 0, i64 0
  %r52 = ptrtoint i8* %r51 to i64
  %r53 = and i64 %r52, 281474976710655
  %r50 = or i64 %r53, 18445618173802708992
  %r54 = getelementptr [9 x i8], [9 x i8]* @.str.112, i64 0, i64 0
  %r55 = ptrtoint i8* %r54 to i64
  %r56 = and i64 %r55, 281474976710655
  %r57 = or i64 %r56, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r57, i64 %r50)
  %r59 = getelementptr [18 x i8], [18 x i8]* @.str.113, i64 0, i64 0
  %r60 = ptrtoint i8* %r59 to i64
  %r61 = and i64 %r60, 281474976710655
  %r58 = or i64 %r61, 18445618173802708992
  %r62 = getelementptr [12 x i8], [12 x i8]* @.str.114, i64 0, i64 0
  %r63 = ptrtoint i8* %r62 to i64
  %r64 = and i64 %r63, 281474976710655
  %r65 = or i64 %r64, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r65, i64 %r58)
  %r67 = getelementptr [16 x i8], [16 x i8]* @.str.115, i64 0, i64 0
  %r68 = ptrtoint i8* %r67 to i64
  %r69 = and i64 %r68, 281474976710655
  %r66 = or i64 %r69, 18445618173802708992
  %r70 = getelementptr [10 x i8], [10 x i8]* @.str.116, i64 0, i64 0
  %r71 = ptrtoint i8* %r70 to i64
  %r72 = and i64 %r71, 281474976710655
  %r73 = or i64 %r72, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r73, i64 %r66)
  %r75 = getelementptr [15 x i8], [15 x i8]* @.str.117, i64 0, i64 0
  %r76 = ptrtoint i8* %r75 to i64
  %r77 = and i64 %r76, 281474976710655
  %r74 = or i64 %r77, 18445618173802708992
  %r78 = getelementptr [9 x i8], [9 x i8]* @.str.118, i64 0, i64 0
  %r79 = ptrtoint i8* %r78 to i64
  %r80 = and i64 %r79, 281474976710655
  %r81 = or i64 %r80, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r81, i64 %r74)
  %r83 = getelementptr [8 x i8], [8 x i8]* @.str.86, i64 0, i64 0
  %r84 = ptrtoint i8* %r83 to i64
  %r85 = and i64 %r84, 281474976710655
  %r82 = or i64 %r85, 18445618173802708992
  %r86 = getelementptr [8 x i8], [8 x i8]* @.str.86, i64 0, i64 0
  %r87 = ptrtoint i8* %r86 to i64
  %r88 = and i64 %r87, 281474976710655
  %r89 = or i64 %r88, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r89, i64 %r82)
  %r91 = getelementptr [7 x i8], [7 x i8]* @.str.58, i64 0, i64 0
  %r92 = ptrtoint i8* %r91 to i64
  %r93 = and i64 %r92, 281474976710655
  %r90 = or i64 %r93, 18445618173802708992
  %r94 = getelementptr [7 x i8], [7 x i8]* @.str.58, i64 0, i64 0
  %r95 = ptrtoint i8* %r94 to i64
  %r96 = and i64 %r95, 281474976710655
  %r97 = or i64 %r96, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r97, i64 %r90)
  %r99 = getelementptr [10 x i8], [10 x i8]* @.str.119, i64 0, i64 0
  %r100 = ptrtoint i8* %r99 to i64
  %r101 = and i64 %r100, 281474976710655
  %r98 = or i64 %r101, 18445618173802708992
  %r102 = getelementptr [10 x i8], [10 x i8]* @.str.119, i64 0, i64 0
  %r103 = ptrtoint i8* %r102 to i64
  %r104 = and i64 %r103, 281474976710655
  %r105 = or i64 %r104, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r105, i64 %r98)
  %r107 = getelementptr [10 x i8], [10 x i8]* @.str.120, i64 0, i64 0
  %r108 = ptrtoint i8* %r107 to i64
  %r109 = and i64 %r108, 281474976710655
  %r106 = or i64 %r109, 18445618173802708992
  %r110 = getelementptr [10 x i8], [10 x i8]* @.str.120, i64 0, i64 0
  %r111 = ptrtoint i8* %r110 to i64
  %r112 = and i64 %r111, 281474976710655
  %r113 = or i64 %r112, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r113, i64 %r106)
  %r115 = getelementptr [12 x i8], [12 x i8]* @.str.62, i64 0, i64 0
  %r116 = ptrtoint i8* %r115 to i64
  %r117 = and i64 %r116, 281474976710655
  %r114 = or i64 %r117, 18445618173802708992
  %r118 = getelementptr [12 x i8], [12 x i8]* @.str.62, i64 0, i64 0
  %r119 = ptrtoint i8* %r118 to i64
  %r120 = and i64 %r119, 281474976710655
  %r121 = or i64 %r120, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r121, i64 %r114)
  %r123 = getelementptr [6 x i8], [6 x i8]* @.str.121, i64 0, i64 0
  %r124 = ptrtoint i8* %r123 to i64
  %r125 = and i64 %r124, 281474976710655
  %r122 = or i64 %r125, 18445618173802708992
  %r126 = getelementptr [8 x i8], [8 x i8]* @.str.122, i64 0, i64 0
  %r127 = ptrtoint i8* %r126 to i64
  %r128 = and i64 %r127, 281474976710655
  %r129 = or i64 %r128, 18445618173802708992
  call void @tscl_object_set(i64 %r0, i64 %r129, i64 %r122)
  store i64 %r0, i64* %local0
  %r131 = getelementptr [24 x i8], [24 x i8]* @.str.123, i64 0, i64 0
  %r132 = ptrtoint i8* %r131 to i64
  %r133 = and i64 %r132, 281474976710655
  %r130 = or i64 %r133, 18445618173802708992
  %r134 = load i64, i64* %local0
  %r136 = getelementptr [8 x i8], [8 x i8]* @.str.122, i64 0, i64 0
  %r137 = ptrtoint i8* %r136 to i64
  %r138 = and i64 %r137, 281474976710655
  %r139 = or i64 %r138, 18445618173802708992
  %r135 = call i64 @tscl_object_get(i64 %r134, i64 %r139)
  %r140 = call i64 @tscl_add_any(i64 %r130, i64 %r135)
  %r142 = getelementptr [2 x i8], [2 x i8]* @.str.124, i64 0, i64 0
  %r143 = ptrtoint i8* %r142 to i64
  %r144 = and i64 %r143, 281474976710655
  %r141 = or i64 %r144, 18445618173802708992
  %r145 = call i64 @tscl_add_any(i64 %r140, i64 %r141)
  %r146 = call i64 @tscl_console_log(i64 %r145)
  %r148 = getelementptr [9 x i8], [9 x i8]* @.str.125, i64 0, i64 0
  %r149 = ptrtoint i8* %r148 to i64
  %r150 = and i64 %r149, 281474976710655
  %r147 = or i64 %r150, 18445618173802708992
  %r152 = getelementptr [10 x i8], [10 x i8]* @.str.126, i64 0, i64 0
  %r153 = ptrtoint i8* %r152 to i64
  %r154 = and i64 %r153, 281474976710655
  %r151 = or i64 %r154, 18445618173802708992
  %r155 = call i64 @tscl_ne_any(i64 %r147, i64 %r151)
  %r157 = getelementptr [9 x i8], [9 x i8]* @.str.125, i64 0, i64 0
  %r158 = ptrtoint i8* %r157 to i64
  %r159 = and i64 %r158, 281474976710655
  %r156 = or i64 %r159, 18445618173802708992
  %r160 = call i64 @tscl_array_length(i64 %r156)
  %r162 = call i64 @tscl_box_number(double 0.0)
  %r163 = call i64 @tscl_gt_any(i64 %r160, i64 %r162)
  %r164 = and i64 %r155, %r163
  %r165 = and i64 %r164, 1
  %r166 = icmp ne i64 %r165, 0
  br i1 %r166, label %if_then_6, label %if_else_7
if_then_6:
  %r168 = getelementptr [9 x i8], [9 x i8]* @.str.125, i64 0, i64 0
  %r169 = ptrtoint i8* %r168 to i64
  %r170 = and i64 %r169, 281474976710655
  %r167 = or i64 %r170, 18445618173802708992
  %r171 = call i64 @main(i64 %r167)
  br label %if_merge_8
if_else_7:
  br label %if_merge_8
if_merge_8:
  %r173 = call i64 @tscl_box_number(double 0.0)
  %r175 = call i64 @tscl_box_number(double 0.0)
  ret i64 9221120237041090561
}

; ============================================================
; Function: __anon_1
; ============================================================
define i64 @__anon_1(i64 %p0) {
entry:
  %local0 = alloca i64
  %local1 = alloca i64
  store i64 %p0, i64* %local0
  br label %__anon_1_entry
__anon_1_entry:
  %r0 = load i64, i64* %local0
  %r1 = call i64 @parseSource(i64 %r0)
  store i64 %r1, i64* %local1
  %r2 = load i64, i64* %local1
  %r3 = add i64 0, 9221120237041090561
  %r4 = call i64 @tscl_eq_any(i64 %r2, i64 %r3)
  %r5 = and i64 %r4, 1
  %r6 = icmp ne i64 %r5, 0
  br i1 %r6, label %if_then_0, label %if_else_1
if_then_0:
  %r7 = add i64 0, 9221120237041090561
  ret i64 %r7
if_else_1:
  br label %if_merge_2
if_merge_2:
  %r8 = load i64, i64* %local1
  %r10 = getelementptr [8 x i8], [8 x i8]* @.str.86, i64 0, i64 0
  %r11 = ptrtoint i8* %r10 to i64
  %r12 = and i64 %r11, 281474976710655
  %r9 = or i64 %r12, 18445618173802708992
  %r14 = getelementptr [11 x i8], [11 x i8]* @.str.87, i64 0, i64 0
  %r15 = ptrtoint i8* %r14 to i64
  %r16 = and i64 %r15, 281474976710655
  %r17 = or i64 %r16, 18445618173802708992
  %r13 = call i64 @tscl_object_get(i64 %r9, i64 %r17)
  %r18 = call i64 %r13(i64 %r8)
  ret i64 %r18
}

; ============================================================
; Function: __anon_2
; ============================================================
define i64 @__anon_2(i64 %p0) {
entry:
  %local0 = alloca i64
  %local1 = alloca i64
  %local2 = alloca i64
  store i64 %p0, i64* %local0
  br label %__anon_2_entry
__anon_2_entry:
  %r0 = load i64, i64* %local0
  %r1 = call i64 @parseSource(i64 %r0)
  store i64 %r1, i64* %local1
  %r2 = load i64, i64* %local1
  %r3 = add i64 0, 9221120237041090561
  %r4 = call i64 @tscl_eq_any(i64 %r2, i64 %r3)
  %r5 = and i64 %r4, 1
  %r6 = icmp ne i64 %r5, 0
  br i1 %r6, label %if_then_0, label %if_else_1
if_then_0:
  %r7 = add i64 0, 9221120237041090561
  ret i64 %r7
if_else_1:
  br label %if_merge_2
if_merge_2:
  %r8 = load i64, i64* %local1
  %r9 = call i64 @lowerProgramToIr(i64 %r8)
  store i64 %r9, i64* %local2
  %r10 = load i64, i64* %local2
  %r11 = add i64 0, 9221120237041090561
  %r12 = call i64 @tscl_eq_any(i64 %r10, i64 %r11)
  %r13 = and i64 %r12, 1
  %r14 = icmp ne i64 %r13, 0
  br i1 %r14, label %if_then_3, label %if_else_4
if_then_3:
  %r15 = add i64 0, 9221120237041090561
  ret i64 %r15
if_else_4:
  br label %if_merge_5
if_merge_5:
  %r16 = load i64, i64* %local2
  %r17 = call i64 @emitLlvmModule(i64 %r16)
  ret i64 %r17
}

; ============================================================
; Main entry point
; ============================================================
define i64 @tscl_box_number(double %val) {
entry:
  %result = bitcast double %val to i64
  ret i64 %result
}

define i32 @main() {
entry:
  call i64 @script_main()
  ret i32 0
}

