mod vm;
mod compiler;

use swc_common::{sync::Lrc, FileName, SourceMap};
use swc_ecma_parser::{lexer::Lexer, Parser, StringInput, Syntax};
use crate::vm::{VM, native_log};
use crate::compiler::borrow_ck::BorrowChecker;
use crate::compiler::Codegen;
use crate::vm::value::*;
use std::collections::HashMap;

#[cfg(test)]
mod tests;

fn main() {
    let cm: Lrc<SourceMap> = Default::default();
    
    // TEST CASE: Using 'a' twice should fail the Borrow Checker
    let code = "let count = 3;
while (count > 0) {
    console.log(count);
    count = count - 1;
}"; 
    
    let fm = cm.new_source_file(FileName::Custom("input.js".into()).into(), code);
    let lexer = Lexer::new(
        Syntax::Es(Default::default()),
        Default::default(),
        StringInput::from(&*fm),
        None,
    );

    let mut parser = Parser::new_from(lexer);
    let module = parser.parse_module().expect("Parse failed");

    // 1. RUN BORROW CHECKER
    let mut bc = BorrowChecker::new();
    for item in &module.body {
        if let Some(stmt) = item.as_stmt() {
            if let Err(e) = bc.analyze_stmt(stmt) {
                eprintln!("BORROW CHECK ERROR: {}", e);
                return;
            }
        }
    }

    // 2. Codegen (Generate Bytecode)
    let mut cg = Codegen::new();
    let bytecode = cg.generate(&module);
    
    println!("Generated Bytecode:");
    for (i, op) in bytecode.iter().enumerate() {
        println!("  {:04}: {:?}", i, op);
    }

    // 3. Execution (VM)
    let mut my_vm = VM::new();
    my_vm.native_functions.push(native_log);

    let console_ptr = my_vm.heap.len();
    let mut console_props = HashMap::new();
    // The index 0 corresponds to the native_log we just pushed
    console_props.insert("log".to_string(), JsValue::NativeFunction(0));

    my_vm.heap.push(HeapObject {
        data: HeapData::Object(console_props),
    });

    // 3. Inject 'console' into the Global Frame (Frame 0)
    my_vm.call_stack[0].locals.insert("console".to_string(), JsValue::Object(console_ptr));
    println!("\nStarting VM Execution:");
    my_vm.run(bytecode);
}